// Generated by tools/build_data.py from the 你好法语1 默写 PDFs.
window.BOOKS = [{
 "id": "nihao1",
 "title": "你好法语 1",
 "fr": "Bonjour ! Le français 1",
 "units": [
  {
   "n": 1,
   "lecons": [
    {
     "n": 1,
     "title": "Bienvenue !",
     "zh": "欢迎",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "您好，早上好",
       "pos": "n.m.",
       "fr": "bonjour"
      },
      {
       "g": "阳性名词",
       "zh": "丈夫",
       "pos": "n.m.",
       "fr": "mari"
      },
      {
       "g": "阳性名词",
       "zh": "先生",
       "pos": "n.m.",
       "fr": "monsieur"
      },
      {
       "g": "阳性名词",
       "zh": "姓氏",
       "pos": "n.m.",
       "fr": "nom"
      },
      {
       "g": "阳性名词",
       "zh": "名字",
       "pos": "n.m.",
       "fr": "prénom"
      },
      {
       "g": "阴性名词",
       "zh": "欢迎",
       "pos": "n.f.",
       "fr": "bienvenue"
      },
      {
       "g": "阴性名词",
       "zh": "女人；妻子",
       "pos": "n.f.",
       "fr": "femme"
      },
      {
       "g": "阴性名词",
       "zh": "夫人",
       "pos": "n.f.",
       "fr": "madame (pl. mesdames)"
      },
      {
       "g": "阴性名词",
       "zh": "国籍",
       "pos": "n.f.",
       "fr": "nationalité"
      },
      {
       "g": "名词",
       "zh": "大学生",
       "pos": "n.",
       "fr": "étudiant(e)"
      },
      {
       "g": "名词",
       "zh": "法国人",
       "pos": "n.",
       "fr": "Français(e)"
      },
      {
       "g": "名词",
       "zh": "意大利人",
       "pos": "n.",
       "fr": "Italien(ne)"
      },
      {
       "g": "动词",
       "zh": "名叫",
       "pos": "v.pr.",
       "fr": "appeler (s')"
      },
      {
       "g": "动词",
       "zh": "是",
       "pos": "v.i.",
       "fr": "être"
      },
      {
       "g": "形容词",
       "zh": "法国的",
       "pos": "adj.",
       "fr": "français(e)"
      },
      {
       "g": "形容词",
       "zh": "意大利的",
       "pos": "adj.",
       "fr": "italien(ne)"
      },
      {
       "g": "形容词",
       "zh": "我的（后接单数阴性名词）",
       "pos": "adj.poss.",
       "fr": "ma"
      },
      {
       "g": "形容词",
       "zh": "我的（后接单数阳性名词）",
       "pos": "adj.poss.",
       "fr": "mon"
      },
      {
       "g": "代词",
       "zh": "这",
       "pos": "pron.dém.",
       "fr": "ce"
      },
      {
       "g": "代词",
       "zh": "她，它（做主语）",
       "pos": "pron.pers.",
       "fr": "elle"
      },
      {
       "g": "代词",
       "zh": "他，它（做主语）",
       "pos": "pron.pers.",
       "fr": "il"
      },
      {
       "g": "代词",
       "zh": "我（做主语）",
       "pos": "pron.pers.",
       "fr": "je"
      },
      {
       "g": "代词",
       "zh": "谁",
       "pos": "pron.interr.",
       "fr": "qui"
      },
      {
       "g": "代词",
       "zh": "你（做主语）",
       "pos": "pron.pers.",
       "fr": "tu"
      },
      {
       "g": "代词",
       "zh": "您；你们（做主语）",
       "pos": "pron.pers.",
       "fr": "vous"
      },
      {
       "g": "副词",
       "zh": "不",
       "pos": "adv.",
       "fr": "non"
      },
      {
       "g": "副词",
       "zh": "对，是的",
       "pos": "adv.",
       "fr": "oui"
      },
      {
       "g": "介词、连词",
       "zh": "和，而，且",
       "pos": "conj.",
       "fr": "et"
      },
      {
       "g": "介词、连词",
       "zh": "这是，这儿是，这就是",
       "pos": "prép.",
       "fr": "voici"
      }
     ],
     "cloze": [
      [
       "对话 1"
      ],
      [
       "– Bonjour, monsieur. Vous ",
       {
        "b": "vous"
       },
       " appelez… ?"
      ],
      [
       "– Doucet. Yves Doucet. Et ",
       {
        "b": "voici"
       },
       " ma femme, Alice."
      ],
      [
       "– Bonjour, ",
       {
        "b": "madame"
       },
       "."
      ],
      [
       "对话 2"
      ],
      [
       "– Bonjour. Je suis Alice Doucet. Vous ",
       {
        "b": "êtes"
       },
       " madame Falco ?"
      ],
      [
       "– Bonjour. Oui, je m'",
       {
        "b": "appelle"
       },
       " Nicole Falco. Aldo, mon ",
       {
        "b": "mari"
       },
       "."
      ],
      [
       "– Arnaud ?"
      ],
      [
       "– Non. Aldo. Il s'appelle Aldo."
      ],
      [
       "对话 3"
      ],
      [
       "– Qui ",
       {
        "b": "est"
       },
       "-ce ?"
      ],
      [
       "– C'est Aldo. Aldo Falco."
      ],
      [
       "– Aldo ? Il ",
       {
        "b": "est"
       },
       " italien ?"
      ],
      [
       "– Oui, et ",
       {
        "b": "elle"
       },
       ", c'est Nicole, ",
       {
        "b": "elle"
       },
       " est ",
       {
        "b": "française"
       },
       "."
      ],
      [
       "对话 4"
      ],
      [
       "– Tu t'appelles Giacomo ! Tu es ",
       {
        "b": "italien"
       },
       " ?"
      ],
      [
       "– Oui, oui. Je ",
       {
        "b": "suis"
       },
       " italien."
      ]
     ],
     "text": [
      {
       "h": "对话 1"
      },
      {
       "zh": "– 您好，先生。您叫……？",
       "fr": "– Bonjour, monsieur. Vous vous appelez… ?"
      },
      {
       "zh": "– Doucet。Yves Doucet。这是我夫人，Alice。",
       "fr": "– Doucet. Yves Doucet. Et voici ma femme, Alice."
      },
      {
       "zh": "– 您好，夫人。",
       "fr": "– Bonjour, madame."
      },
      {
       "h": "对话 2"
      },
      {
       "zh": "– 您好。我是 Alice Doucet。您是 Falco 夫人吗？",
       "fr": "– Bonjour. Je suis Alice Doucet. Vous êtes madame Falco ?"
      },
      {
       "zh": "– 您好。是的，我叫 Nicole Falco。这是 Aldo，我丈夫。",
       "fr": "– Bonjour. Oui, je m'appelle Nicole Falco. Aldo, mon mari."
      },
      {
       "zh": "– Arnaud ？",
       "fr": "– Arnaud ?"
      },
      {
       "zh": "– 不。Aldo。他叫 Aldo。",
       "fr": "– Non. Aldo. Il s'appelle Aldo."
      },
      {
       "h": "对话 3"
      },
      {
       "zh": "– 这是谁？",
       "fr": "– Qui est-ce ?"
      },
      {
       "zh": "– 这是 Aldo。Aldo Falco。",
       "fr": "– C'est Aldo. Aldo Falco."
      },
      {
       "zh": "– Aldo ？他是意大利人吗？",
       "fr": "– Aldo ? Il est italien ?"
      },
      {
       "zh": "– 是的。她呢，是 Nicole，她是法国人。",
       "fr": "– Oui, et elle, c'est Nicole, elle est française."
      },
      {
       "h": "对话 4"
      },
      {
       "zh": "– 你叫 Giacomo ！你是意大利人吗？",
       "fr": "– Tu t'appelles Giacomo ! Tu es italien ?"
      },
      {
       "zh": "– 对，对。我是意大利人。",
       "fr": "– Oui, oui. Je suis italien."
      }
     ]
    },
    {
     "n": 2,
     "title": "Qui est-ce ?",
     "zh": "这是谁？",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "咖啡；咖啡馆",
       "pos": "n.m.",
       "fr": "café"
      },
      {
       "g": "阳性名词",
       "zh": "课，课程",
       "pos": "n.m.",
       "fr": "cours"
      },
      {
       "g": "阳性名词",
       "zh": "法语",
       "pos": "n.m.",
       "fr": "français"
      },
      {
       "g": "阳性名词",
       "zh": "日本",
       "pos": "n.m.",
       "fr": "Japon"
      },
      {
       "g": "阳性名词",
       "zh": "中学教师；大学教授；教员，教练",
       "pos": "n.m.",
       "fr": "professeur"
      },
      {
       "g": "阳性名词",
       "zh": "约会，预约",
       "pos": "n.m.",
       "fr": "rendez-vous"
      },
      {
       "g": "阳性名词",
       "zh": "电话；电话机",
       "pos": "n.m.",
       "fr": "téléphone"
      },
      {
       "g": "阳性名词",
       "zh": "（泡好的）茶；茶叶",
       "pos": "n.m.",
       "fr": "thé"
      },
      {
       "g": "阴性名词",
       "zh": "法国",
       "pos": "n.f.",
       "fr": "France"
      },
      {
       "g": "阴性名词",
       "zh": "瑞士",
       "pos": "n.f.",
       "fr": "Suisse"
      },
      {
       "g": "名词",
       "zh": "助理，助手，副手",
       "pos": "n.",
       "fr": "assistant(e)"
      },
      {
       "g": "名词",
       "zh": "比利时人",
       "pos": "n.",
       "fr": "Belge"
      },
      {
       "g": "名词",
       "zh": "中国人",
       "pos": "n.",
       "fr": "Chinois(e)"
      },
      {
       "g": "名词",
       "zh": "经理",
       "pos": "n.",
       "fr": "directeur(trice)"
      },
      {
       "g": "名词",
       "zh": "西班牙人",
       "pos": "n.",
       "fr": "Espagnol(e)"
      },
      {
       "g": "名词",
       "zh": "日本人",
       "pos": "n.",
       "fr": "Japonais(e)"
      },
      {
       "g": "名词",
       "zh": "秘书",
       "pos": "n.",
       "fr": "secrétaire"
      },
      {
       "g": "动词",
       "zh": "居住（在）",
       "pos": "v.",
       "fr": "habiter"
      },
      {
       "g": "形容词",
       "zh": "比利时的",
       "pos": "adj.",
       "fr": "belge"
      },
      {
       "g": "形容词",
       "zh": "中国的",
       "pos": "adj.",
       "fr": "chinois(e)"
      },
      {
       "g": "形容词",
       "zh": "西班牙的",
       "pos": "adj.",
       "fr": "espagnol(e)"
      },
      {
       "g": "形容词",
       "zh": "日本的",
       "pos": "adj.",
       "fr": "japonais(e)"
      },
      {
       "g": "形容词",
       "zh": "（俗）给人好感的，讨人喜欢的",
       "pos": "adj.inv.",
       "fr": "sympa"
      },
      {
       "g": "介词、连词",
       "zh": "在；向，到；给……",
       "pos": "prép.",
       "fr": "à"
      },
      {
       "g": "介词、连词",
       "zh": "在……里；处于……",
       "pos": "prép.",
       "fr": "dans"
      },
      {
       "g": "介词、连词",
       "zh": "在……（指地点）",
       "pos": "prép.",
       "fr": "en"
      },
      {
       "g": "介词、连词",
       "zh": "或，或者，还是（表示选择）",
       "pos": "conj.",
       "fr": "ou"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "啊！唉！",
       "pos": "interj.",
       "fr": "ah"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "（医生接待）预约就诊（的病人）",
       "pos": "",
       "fr": "sur rendez-vous"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "请，请您，请问",
       "pos": "loc.",
       "fr": "s'il vous plaît"
      },
      {
       "g": "地名",
       "zh": "日内瓦（瑞士）",
       "pos": "",
       "fr": "Genève"
      }
     ],
     "cloze": [
      [
       "– Qui est-ce ?"
      ],
      [
       "– C'",
       {
        "b": "est"
       },
       " Naoko, non ?"
      ],
      [
       "– Naoko ?"
      ],
      [
       "– Oui, Naoko Yamada. Elle ",
       {
        "b": "est"
       },
       " étudiante."
      ],
      [
       "– Elle ",
       {
        "b": "est"
       },
       " sympa ?"
      ],
      [
       "– Oui. Elle ",
       {
        "b": "est"
       },
       " dans le ",
       {
        "b": "cours"
       },
       " de français, ",
       {
        "b": "elle"
       },
       " est ",
       {
        "b": "japonaise"
       },
       "."
      ],
      [
       "– Elle habite en France ou au Japon ?"
      ],
      [
       "– Elle ",
       {
        "b": "habite"
       },
       " en Suisse, à Genève."
      ]
     ],
     "text": [
      {
       "zh": "– 这是谁？",
       "fr": "– Qui est-ce ?"
      },
      {
       "zh": "– 这是 Naoko，不是吗？",
       "fr": "– C'est Naoko, non ?"
      },
      {
       "zh": "– Naoko ？",
       "fr": "– Naoko ?"
      },
      {
       "zh": "– 是的，Naoko Yamada。她是大学生。",
       "fr": "– Oui, Naoko Yamada. Elle est étudiante."
      },
      {
       "zh": "– 她人好吗？",
       "fr": "– Elle est sympa ?"
      },
      {
       "zh": "– 是的。她在法语班上，她是日本人。",
       "fr": "– Oui. Elle est dans le cours de français, elle est japonaise."
      },
      {
       "zh": "– 她住在 France 还是 Japon ？",
       "fr": "– Elle habite en France ou au Japon ?"
      },
      {
       "zh": "– 她住在 Suisse，在 Genève。",
       "fr": "– Elle habite en Suisse, à Genève."
      }
     ]
    },
    {
     "n": 3,
     "title": "Ça va bien ?",
     "zh": "你好吗？",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "年龄，年纪",
       "pos": "n.m.",
       "fr": "âge"
      },
      {
       "g": "阳性名词",
       "zh": "婴儿；孩子，宝宝",
       "pos": "n.m.",
       "fr": "bébé"
      },
      {
       "g": "阳性名词",
       "zh": "加拿大",
       "pos": "n.m.",
       "fr": "Canada"
      },
      {
       "g": "阳性名词",
       "zh": "电子邮件",
       "pos": "n.m.",
       "fr": "e-mail"
      },
      {
       "g": "阳性名词",
       "zh": "儿子",
       "pos": "n.m.",
       "fr": "fils"
      },
      {
       "g": "阳性名词",
       "zh": "男孩；小伙子",
       "pos": "n.m.",
       "fr": "garçon"
      },
      {
       "g": "阴性名词",
       "zh": "地址，住址",
       "pos": "n.f.",
       "fr": "adresse"
      },
      {
       "g": "阴性名词",
       "zh": "女孩，姑娘；女儿",
       "pos": "n.f.",
       "fr": "fille"
      },
      {
       "g": "阴性名词",
       "zh": "一天，一昼夜；白天，白昼",
       "pos": "n.f.",
       "fr": "journée"
      },
      {
       "g": "阴性名词",
       "zh": "圣母院",
       "pos": "n.f.inv.",
       "fr": "Notre-Dame"
      },
      {
       "g": "阴性名词",
       "zh": "街，街道，马路",
       "pos": "n.f.",
       "fr": "rue"
      },
      {
       "g": "名词",
       "zh": "朋友",
       "pos": "n.",
       "fr": "ami(e)"
      },
      {
       "g": "动词",
       "zh": "去，走；处于……的健康状况；运转，进行，进展",
       "pos": "v.i.",
       "fr": "aller"
      },
      {
       "g": "动词",
       "zh": "有，拥有，具有，享有，带有",
       "pos": "v.t.",
       "fr": "avoir"
      },
      {
       "g": "动词",
       "zh": "说话，讲话；交谈 / 讲（某种语言）",
       "pos": "v.i. / v.t.dir.",
       "fr": "parler"
      },
      {
       "g": "形容词",
       "zh": "什么样的，哪一类的",
       "pos": "adj.interr.",
       "fr": "quel(le)"
      },
      {
       "g": "形容词",
       "zh": "他的，她的，它的（后接单数阳性名词）",
       "pos": "adj.poss.",
       "fr": "son"
      },
      {
       "g": "形容词",
       "zh": "你的（后接单数阳性名词）",
       "pos": "adj.poss.",
       "fr": "ton"
      },
      {
       "g": "形容词",
       "zh": "你们的，您的（后接单数名词）",
       "pos": "adj.poss.",
       "fr": "votre"
      },
      {
       "g": "代词",
       "zh": "（俗）这个，那个",
       "pos": "pron.dém.",
       "fr": "ça"
      },
      {
       "g": "代词",
       "zh": "你（用作主语或宾语的同位语，表示加强语气）",
       "pos": "pron.pers.",
       "fr": "toi"
      },
      {
       "g": "代词",
       "zh": "您；你们（用作主语或宾语的同位语，表示加强语气）",
       "pos": "pron.pers.",
       "fr": "vous"
      },
      {
       "g": "副词",
       "zh": "那么，在这种情况下",
       "pos": "adv.",
       "fr": "alors"
      },
      {
       "g": "副词",
       "zh": "好",
       "pos": "adv.",
       "fr": "bien"
      },
      {
       "g": "副词",
       "zh": "如何，怎么，怎样",
       "pos": "adv.interr.",
       "fr": "comment"
      },
      {
       "g": "副词",
       "zh": "现在，目前",
       "pos": "adv.",
       "fr": "maintenant"
      },
      {
       "g": "介词、连词",
       "zh": "和……一起",
       "pos": "prép.",
       "fr": "avec"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "谢谢！",
       "pos": "interj.",
       "fr": "merci"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "（俗）（上前与朋友交谈或离开他们时）你好；再见",
       "pos": "interj.",
       "fr": "salut"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "（不确指的）一个，某一……",
       "pos": "art.indéf.",
       "fr": "un(e)"
      },
      {
       "g": "地名",
       "zh": "蒙特利尔（加拿大）",
       "pos": "",
       "fr": "Montréal"
      },
      {
       "g": "地名",
       "zh": "巴黎（法国）",
       "pos": "",
       "fr": "Paris"
      }
     ],
     "cloze": [
      [
       "对话 1"
      ],
      [
       "– Salut, Céline, tu vas ",
       {
        "b": "bien"
       },
       " ?"
      ],
      [
       "– Oui, ça va bien. Et ",
       {
        "b": "toi"
       },
       " ?"
      ],
      [
       "– Je vais ",
       {
        "b": "bien"
       },
       ", merci… J'",
       {
        "b": "habite"
       },
       " à Montréal, maintenant, ",
       {
        "b": "avec"
       },
       " ma femme."
      ],
      [
       "– Au Canada ?"
      ],
      [
       "– Oui, ",
       {
        "b": "oui"
       },
       ", au Canada."
      ],
      [
       "– Ah ! C'est ",
       {
        "b": "bien"
       },
       ". Et quelle ",
       {
        "b": "est"
       },
       " ton ",
       {
        "b": "adresse"
       },
       " ?"
      ],
      [
       "– Mon adresse ? Alors, c'",
       {
        "b": "est"
       },
       " : David Delage… 35, rue Notre-Dame, à Montréal."
      ],
      [
       "– Et tu as ",
       {
        "b": "une"
       },
       " adresse e-",
       {
        "b": "mail"
       },
       " ?"
      ],
      [
       "– Oui, c'est : ddelage@hotmail.com."
      ],
      [
       "对话 2"
      ],
      [
       "– Comment va ",
       {
        "b": "ton"
       },
       " ami ",
       {
        "b": "espagnol"
       },
       " ?"
      ],
      [
       "– Luis ? Il va bien. Il ",
       {
        "b": "est"
       },
       " à Paris avec ",
       {
        "b": "son"
       },
       " fils. Il ",
       {
        "b": "parle"
       },
       " français ",
       {
        "b": "maintenant"
       },
       "."
      ],
      [
       "– Tu as son ",
       {
        "b": "adresse"
       },
       " ?"
      ]
     ],
     "text": [
      {
       "h": "对话 1"
      },
      {
       "zh": "– 你好，Céline，你好吗？",
       "fr": "– Salut, Céline, tu vas bien ?"
      },
      {
       "zh": "– 挺好的。你呢？",
       "fr": "– Oui, ça va bien. Et toi ?"
      },
      {
       "zh": "– 我很好，谢谢……我现在和我妻子住在 Montréal。",
       "fr": "– Je vais bien, merci… J'habite à Montréal, maintenant, avec ma femme."
      },
      {
       "zh": "– 在 Canada ？",
       "fr": "– Au Canada ?"
      },
      {
       "zh": "– 对，对，在 Canada。",
       "fr": "– Oui, oui, au Canada."
      },
      {
       "zh": "– 啊！太好了！那你的地址是什么？",
       "fr": "– Ah ! C'est bien. Et quelle est ton adresse ?"
      },
      {
       "zh": "– 我的地址？嗯，是：David Delage……Montréal，Notre-Dame 街 35 号。",
       "fr": "– Mon adresse ? Alors, c'est : David Delage… 35, rue Notre-Dame, à Montréal."
      },
      {
       "zh": "– 你有电子邮箱吗？",
       "fr": "– Et tu as une adresse e-mail ?"
      },
      {
       "zh": "– 有，是：ddelage@hotmail.com。",
       "fr": "– Oui, c'est : ddelage@hotmail.com."
      },
      {
       "h": "对话 2"
      },
      {
       "zh": "– 你的西班牙朋友好吗？",
       "fr": "– Comment va ton ami espagnol ?"
      },
      {
       "zh": "– Luis ？他很好。他和他儿子在 Paris。他现在会说法语了。",
       "fr": "– Luis ? Il va bien. Il est à Paris avec son fils. Il parle français maintenant."
      },
      {
       "zh": "– 你有他的地址吗？",
       "fr": "– Tu as son adresse ?"
      }
     ]
    },
    {
     "n": 4,
     "title": "Correspondants",
     "zh": "寻找笔友",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "年；岁",
       "pos": "n.m.",
       "fr": "an"
      },
      {
       "g": "阳性名词",
       "zh": "电影，电影艺术；电影院",
       "pos": "n.m.",
       "fr": "cinéma"
      },
      {
       "g": "阳性名词",
       "zh": "西班牙语",
       "pos": "n.m.",
       "fr": "espagnol"
      },
      {
       "g": "阳性名词",
       "zh": "高尔夫球运动",
       "pos": "n.m.",
       "fr": "golf"
      },
      {
       "g": "阳性名词",
       "zh": "世界",
       "pos": "n.m.",
       "fr": "monde"
      },
      {
       "g": "阳性名词",
       "zh": "塞内加尔",
       "pos": "n.m.",
       "fr": "Sénégal"
      },
      {
       "g": "阳性名词",
       "zh": "运动，体育运动，运动项目",
       "pos": "n.m.",
       "fr": "sport"
      },
      {
       "g": "阳性名词",
       "zh": "排球，排球运动",
       "pos": "n.m.",
       "fr": "volley-ball"
      },
      {
       "g": "阴性名词",
       "zh": "比利时",
       "pos": "n.f.",
       "fr": "Belgique"
      },
      {
       "g": "阴性名词",
       "zh": "通信，通信联系；（集）书信，信件",
       "pos": "n.f.",
       "fr": "correspondance"
      },
      {
       "g": "阴性名词",
       "zh": "舞蹈",
       "pos": "n.f.",
       "fr": "danse"
      },
      {
       "g": "阴性名词",
       "zh": "欧洲",
       "pos": "n.f.",
       "fr": "Europe"
      },
      {
       "g": "阴性名词",
       "zh": "阅读",
       "pos": "n.f.",
       "fr": "lecture"
      },
      {
       "g": "阴性名词",
       "zh": "音乐，乐曲",
       "pos": "n.f.",
       "fr": "musique"
      },
      {
       "g": "阴性名词",
       "zh": "自然（界），大自然",
       "pos": "n.f.",
       "fr": "nature"
      },
      {
       "g": "阴性名词",
       "zh": "摄影；照片",
       "pos": "n.f.",
       "fr": "photo"
      },
      {
       "g": "阴性名词",
       "zh": "姐妹",
       "pos": "n.f.",
       "fr": "sœur"
      },
      {
       "g": "名词",
       "zh": "面包师，面包商",
       "pos": "n.",
       "fr": "boulanger(ère)"
      },
      {
       "g": "名词",
       "zh": "通信者，有信件来往者",
       "pos": "n.",
       "fr": "correspondant(e)"
      },
      {
       "g": "动词",
       "zh": "爱，热爱",
       "pos": "v.t.",
       "fr": "aimer"
      },
      {
       "g": "动词",
       "zh": "找，寻找，寻觅",
       "pos": "v.t.",
       "fr": "chercher"
      },
      {
       "g": "形容词",
       "zh": "古典的",
       "pos": "adj.",
       "fr": "classique"
      },
      {
       "g": "形容词",
       "zh": "圭亚那的",
       "pos": "n.",
       "fr": "guyanais(e)"
      },
      {
       "g": "形容词",
       "zh": "魁北克的",
       "pos": "adj.",
       "fr": "québécois(e)"
      },
      {
       "g": "代词",
       "zh": "我（用作主语或宾语的同位语，以加强语气）",
       "pos": "pron.pers.",
       "fr": "moi"
      },
      {
       "g": "副词",
       "zh": "也",
       "pos": "adv.",
       "fr": "aussi"
      },
      {
       "g": "副词",
       "zh": "很，非常；很多",
       "pos": "adv.",
       "fr": "beaucoup"
      },
      {
       "g": "副词",
       "zh": "经常，常常",
       "pos": "adv.",
       "fr": "souvent"
      },
      {
       "g": "副词",
       "zh": "一点儿，一下，少许，稍微",
       "pos": "loc.adv.",
       "fr": "un peu"
      },
      {
       "g": "介词、连词",
       "zh": "（表示动作的起点、由来）从，自",
       "pos": "prép.",
       "fr": "de"
      },
      {
       "g": "地名",
       "zh": "布鲁塞尔（比利时）",
       "pos": "",
       "fr": "Bruxelles"
      },
      {
       "g": "地名",
       "zh": "卡宴（法属圭亚那的首府）",
       "pos": "",
       "fr": "Cayenne"
      },
      {
       "g": "地名",
       "zh": "达喀尔（塞内加尔）",
       "pos": "",
       "fr": "Dakar"
      },
      {
       "g": "地名",
       "zh": "洛桑（瑞士）",
       "pos": "",
       "fr": "Lausanne"
      }
     ],
     "cloze": [
      [
       "Diouf"
      ],
      [
       "Salut ! Je m'appelle Diouf. J'ai 29 ",
       {
        "b": "ans"
       },
       ". J'habite à Dakar au Sénégal. Je ",
       {
        "b": "vais"
       },
       " souvent au ",
       {
        "b": "cinéma"
       },
       ". Je cherche un ",
       {
        "b": "correspondant"
       },
       " en France ou au Canada."
      ],
      [
       "Mon e-mail : diouf29@webzine.com"
      ],
      [
       "Antoine"
      ],
      [
       "Je m'",
       {
        "b": "appelle"
       },
       " Antoine. J'ai 25 ans et j'",
       {
        "b": "habite"
       },
       " à Bruxelles, en Belgique. Je suis ",
       {
        "b": "étudiant"
       },
       ". J'aime la ",
       {
        "b": "lecture"
       },
       ", la nature et la ",
       {
        "b": "musique"
       },
       " classique."
      ],
      [
       "Mon e-",
       {
        "b": "mail"
       },
       " : antoine.leconte@webzine.com"
      ],
      [
       "Marion"
      ],
      [
       "Moi, c'est Marion. Je ",
       {
        "b": "suis"
       },
       " québécoise. J'ai 18 ",
       {
        "b": "ans"
       },
       " et j'habite à Montréal. J'",
       {
        "b": "aime"
       },
       " le sport : le ",
       {
        "b": "volley"
       },
       "-ball, le ",
       {
        "b": "golf"
       },
       "… Je cherche ",
       {
        "b": "une"
       },
       " amie en Europe."
      ],
      [
       "Mon e-",
       {
        "b": "mail"
       },
       " : marion@webzine.net"
      ],
      [
       "Pauline"
      ],
      [
       "Bonjour, je m'appelle Pauline et j'ai 31 ",
       {
        "b": "ans"
       },
       ". Je suis ",
       {
        "b": "guyanaise"
       },
       " : j'habite à Cayenne. Je ",
       {
        "b": "suis"
       },
       " secrétaire. Je ",
       {
        "b": "cherche"
       },
       " une ",
       {
        "b": "correspondante"
       },
       " de 30 à 40 ans. Je ",
       {
        "b": "parle"
       },
       " français, ",
       {
        "b": "anglais"
       },
       " et espagnol. J'",
       {
        "b": "aime"
       },
       " beaucoup la ",
       {
        "b": "danse"
       },
       "."
      ],
      [
       "Mon e-mail : pauline31@webzine.fr"
      ],
      [
       "Sandro"
      ],
      [
       "Je m'",
       {
        "b": "appelle"
       },
       " Sandro et j'habite en Suisse, à Lausanne. J'ai 22 ",
       {
        "b": "ans"
       },
       ". Je suis ",
       {
        "b": "boulanger"
       },
       ". J'aime la ",
       {
        "b": "photo"
       },
       "."
      ],
      [
       "Mon e-mail : sandro.carre@webzine.ch"
      ]
     ],
     "text": [
      {
       "h": "Diouf"
      },
      {
       "zh": "你好！我叫 Diouf。我29岁。我住在 Sénégal 的 Dakar。我经常去看电影。我想找一位在 France 或 Canada 的笔友。",
       "fr": "Salut ! Je m'appelle Diouf. J'ai 29 ans. J'habite à Dakar au Sénégal. Je vais souvent au cinéma. Je cherche un correspondant en France ou au Canada."
      },
      {
       "zh": "我的邮箱：diouf29@webzine.com",
       "fr": "Mon e-mail : diouf29@webzine.com"
      },
      {
       "h": "Antoine"
      },
      {
       "zh": "我叫 Antoine。我25岁，住在 Belgique 的 Bruxelles。我是大学生。我喜欢阅读、大自然和古典音乐。",
       "fr": "Je m'appelle Antoine. J'ai 25 ans et j'habite à Bruxelles, en Belgique. Je suis étudiant. J'aime la lecture, la nature et la musique classique."
      },
      {
       "zh": "我的邮箱：antoine.leconte@webzine.com",
       "fr": "Mon e-mail : antoine.leconte@webzine.com"
      },
      {
       "h": "Marion"
      },
      {
       "zh": "我是 Marion。我是魁北克人。我18岁，住在 Montréal。我喜欢运动：排球、高尔夫……我想在 Europe 找一位女性朋友。",
       "fr": "Moi, c'est Marion. Je suis québécoise. J'ai 18 ans et j'habite à Montréal. J'aime le sport : le volley-ball, le golf… Je cherche une amie en Europe."
      },
      {
       "zh": "我的邮箱：marion@webzine.net",
       "fr": "Mon e-mail : marion@webzine.net"
      },
      {
       "h": "Pauline"
      },
      {
       "zh": "你好，我叫 Pauline，31岁。我是圭亚那人，住在 Cayenne。我是秘书。我想找一位30到40岁的女笔友。我会说法语、英语和西班牙语。我非常喜欢舞蹈。",
       "fr": "Bonjour, je m'appelle Pauline et j'ai 31 ans. Je suis guyanaise : j'habite à Cayenne. Je suis secrétaire. Je cherche une correspondante de 30 à 40 ans. Je parle français, anglais et espagnol. J'aime beaucoup la danse."
      },
      {
       "zh": "我的邮箱：pauline31@webzine.fr",
       "fr": "Mon e-mail : pauline31@webzine.fr"
      },
      {
       "h": "Sandro"
      },
      {
       "zh": "我叫 Sandro，住在 Suisse 的 Lausanne。我22岁。我是面包师。我喜欢摄影。",
       "fr": "Je m'appelle Sandro et j'habite en Suisse, à Lausanne. J'ai 22 ans. Je suis boulanger. J'aime la photo."
      },
      {
       "zh": "我的邮箱：sandro.carre@webzine.ch",
       "fr": "Mon e-mail : sandro.carre@webzine.ch"
      }
     ]
    }
   ]
  },
  {
   "n": 2,
   "lecons": [
    {
     "n": 5,
     "title": "Trouvez l'objet",
     "zh": "找出物品",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "夹克衫",
       "pos": "n.m.",
       "fr": "blouson"
      },
      {
       "g": "阳性名词",
       "zh": "帽子",
       "pos": "n.m.",
       "fr": "chapeau"
      },
      {
       "g": "阳性名词",
       "zh": "旁，侧",
       "pos": "n.m.",
       "fr": "côté"
      },
      {
       "g": "阳性名词",
       "zh": "扶手椅",
       "pos": "n.m.",
       "fr": "fauteuil"
      },
      {
       "g": "阳性名词",
       "zh": "床",
       "pos": "n.m.",
       "fr": "lit"
      },
      {
       "g": "阳性名词",
       "zh": "书，书本，书籍",
       "pos": "n.m.",
       "fr": "livre"
      },
      {
       "g": "阳性名词",
       "zh": "墙，壁",
       "pos": "n.m.",
       "fr": "mur"
      },
      {
       "g": "阳性名词",
       "zh": "物，物体；物品，东西",
       "pos": "n.m.",
       "fr": "objet"
      },
      {
       "g": "阳性名词",
       "zh": "电脑",
       "pos": "n.m.",
       "fr": "ordinateur"
      },
      {
       "g": "阳性名词",
       "zh": "包",
       "pos": "n.m.",
       "fr": "sac"
      },
      {
       "g": "阳性名词",
       "zh": "玻璃杯",
       "pos": "n.m.",
       "fr": "verre"
      },
      {
       "g": "阴性名词",
       "zh": "海报，广告",
       "pos": "n.f.",
       "fr": "affiche"
      },
      {
       "g": "阴性名词",
       "zh": "盘子",
       "pos": "n.f.",
       "fr": "assiette"
      },
      {
       "g": "阴性名词",
       "zh": "椅子",
       "pos": "n.f.",
       "fr": "chaise"
      },
      {
       "g": "阴性名词",
       "zh": "房间，卧室",
       "pos": "n.f.",
       "fr": "chambre"
      },
      {
       "g": "阴性名词",
       "zh": "右面，右边，右方",
       "pos": "n.f.",
       "fr": "droite"
      },
      {
       "g": "阴性名词",
       "zh": "(固定在墙上的)格，隔板，架子；多层架子",
       "pos": "n.f.",
       "fr": "étagère"
      },
      {
       "g": "阴性名词",
       "zh": "窗，窗子，窗户，玻璃窗",
       "pos": "n.f.",
       "fr": "fenêtre"
      },
      {
       "g": "阴性名词",
       "zh": "左，左边，左面",
       "pos": "n.f.",
       "fr": "gauche"
      },
      {
       "g": "阴性名词",
       "zh": "桌子",
       "pos": "n.f.",
       "fr": "table"
      },
      {
       "g": "名词",
       "zh": "猫",
       "pos": "n.",
       "fr": "chat(te)"
      },
      {
       "g": "动词",
       "zh": "找到，发现",
       "pos": "v.t.",
       "fr": "trouver"
      },
      {
       "g": "代词",
       "zh": "什么",
       "pos": "pron.interr.",
       "fr": "que"
      },
      {
       "g": "副词",
       "zh": "在下面",
       "pos": "loc.adv.",
       "fr": "au-dessous"
      },
      {
       "g": "副词",
       "zh": "在上面，……以上",
       "pos": "loc.adv.",
       "fr": "au-dessus"
      },
      {
       "g": "介词、连词",
       "zh": "具有，带有",
       "pos": "prép.",
       "fr": "avec"
      },
      {
       "g": "介词、连词",
       "zh": "靠，挨",
       "pos": "prép.",
       "fr": "contre"
      },
      {
       "g": "介词、连词",
       "zh": "在（……的）旁边",
       "pos": "loc.prép.",
       "fr": "à côté (de)"
      },
      {
       "g": "介词、连词",
       "zh": "[表示所属、所有]",
       "pos": "prép.",
       "fr": "de"
      },
      {
       "g": "介词、连词",
       "zh": "在……前面",
       "pos": "prép.",
       "fr": "devant"
      },
      {
       "g": "介词、连词",
       "zh": "在（……的）右边",
       "pos": "loc.prép.",
       "fr": "à droite (de)"
      },
      {
       "g": "介词、连词",
       "zh": "在（……的）左边",
       "pos": "loc.prép.",
       "fr": "à gauche (de)"
      },
      {
       "g": "介词、连词",
       "zh": "在……下面",
       "pos": "prép.",
       "fr": "sous"
      },
      {
       "g": "介词、连词",
       "zh": "在……上面",
       "pos": "prép.",
       "fr": "sur"
      },
      {
       "g": "介词、连词",
       "zh": "那就是，这就是",
       "pos": "prép.",
       "fr": "voilà"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "有……",
       "pos": "",
       "fr": "il y a"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "得啦，好啦，哟；瞧",
       "pos": "interj.",
       "fr": "là"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "啊！哦！呦！哎呀！",
       "pos": "interj.",
       "fr": "oh"
      }
     ],
     "cloze": [
      [
       "– Son chapeau et ",
       {
        "b": "son"
       },
       " blouson, c'",
       {
        "b": "est"
       },
       " ça ?"
      ],
      [
       "– Oui, son ",
       {
        "b": "chapeau"
       },
       " et son ",
       {
        "b": "blouson"
       },
       ". Ils sont ",
       {
        "b": "dans"
       },
       " la chambre de Mélanie, ",
       {
        "b": "sous"
       },
       " l'étagère à ",
       {
        "b": "côté"
       },
       " de la fenêtre."
      ],
      [
       "– L'",
       {
        "b": "étagère"
       },
       " avec ",
       {
        "b": "des"
       },
       " livres, à ",
       {
        "b": "gauche"
       },
       " de la fenêtre ?"
      ],
      [
       "– Non ! L'",
       {
        "b": "étagère"
       },
       " contre le ",
       {
        "b": "mur"
       },
       ", à droite de la ",
       {
        "b": "fenêtre"
       },
       "… sous ",
       {
        "b": "les"
       },
       " affiches ! Oh ! là, là !"
      ],
      [
       "– À ",
       {
        "b": "droite"
       },
       " de… Ah oui ! Sur la ",
       {
        "b": "chaise"
       },
       ", il y a un blouson et un ",
       {
        "b": "chapeau"
       },
       "."
      ],
      [
       "– Voilà ! C'est ça !"
      ]
     ],
     "text": [
      {
       "zh": "– 她的帽子和夹克衫，是这些吗？",
       "fr": "– Son chapeau et son blouson, c'est ça ?"
      },
      {
       "zh": "– 是的，她的帽子和夹克衫。它们在 Mélanie 的房间里，在窗户旁边的架子下面。",
       "fr": "– Oui, son chapeau et son blouson. Ils sont dans la chambre de Mélanie, sous l'étagère à côté de la fenêtre."
      },
      {
       "zh": "– 摆着书、在窗户左边的那个架子吗？",
       "fr": "– L'étagère avec des livres, à gauche de la fenêtre ?"
      },
      {
       "zh": "– 不是！是靠墙、在窗户右边的那个架子……在海报下面！哎呀！",
       "fr": "– Non ! L'étagère contre le mur, à droite de la fenêtre… sous les affiches ! Oh ! là, là !"
      },
      {
       "zh": "– 在……的右边……啊，对了！椅子上有一件夹克衫和一顶帽子。",
       "fr": "– À droite de… Ah oui ! Sur la chaise, il y a un blouson et un chapeau."
      },
      {
       "zh": "– 对了！就是这个！",
       "fr": "– Voilà ! C'est ça !"
      }
     ]
    },
    {
     "n": 6,
     "title": "Portrait-robot",
     "zh": "模拟画像",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "人；男人，男子",
       "pos": "n.m.",
       "fr": "homme"
      },
      {
       "g": "阳性名词",
       "zh": "牛仔裤",
       "pos": "n.m.",
       "fr": "jean"
      },
      {
       "g": "阳性名词",
       "zh": "长裤",
       "pos": "n.m.",
       "fr": "pantalon"
      },
      {
       "g": "阳性名词",
       "zh": "（警方综合搜捕对象的特征所制的）模拟画像",
       "pos": "n.m.",
       "fr": "portrait-robot"
      },
      {
       "g": "阳性名词",
       "zh": "短袖圆领棉汗衫，T恤衫",
       "pos": "n.m.",
       "fr": "tee-shirt"
      },
      {
       "g": "阳性名词",
       "zh": "衣服，服装，衣裳",
       "pos": "n.m.",
       "fr": "vêtement"
      },
      {
       "g": "阴性名词",
       "zh": "篮球鞋，运动鞋（一般用复数）",
       "pos": "n.f.",
       "fr": "basket"
      },
      {
       "g": "阴性名词",
       "zh": "鞋，靴",
       "pos": "n.f.",
       "fr": "chaussure"
      },
      {
       "g": "阴性名词",
       "zh": "男式衬衫",
       "pos": "n.f.",
       "fr": "chemise"
      },
      {
       "g": "阴性名词",
       "zh": "事情，事物",
       "pos": "n.f.",
       "fr": "chose"
      },
      {
       "g": "阴性名词",
       "zh": "色，颜色",
       "pos": "n.f.",
       "fr": "couleur"
      },
      {
       "g": "阴性名词",
       "zh": "眼镜",
       "pos": "n.f.pl.",
       "fr": "lunettes"
      },
      {
       "g": "动词",
       "zh": "穿戴，佩戴",
       "pos": "v.t.",
       "fr": "porter"
      },
      {
       "g": "形容词",
       "zh": "另一个的，别的，另外的",
       "pos": "adj.",
       "fr": "autre"
      },
      {
       "g": "形容词",
       "zh": "白的，白色的",
       "pos": "adj.",
       "fr": "blanc(che)"
      },
      {
       "g": "形容词",
       "zh": "蓝色的，青的",
       "pos": "adj.",
       "fr": "bleu(e)"
      },
      {
       "g": "形容词",
       "zh": "金色的；有金色头发的",
       "pos": "adj.",
       "fr": "blond(e)"
      },
      {
       "g": "形容词",
       "zh": "棕色的；有棕色头发的",
       "pos": "adj.",
       "fr": "brun(e)"
      },
      {
       "g": "形容词",
       "zh": "高大的",
       "pos": "adj.",
       "fr": "grand(e)"
      },
      {
       "g": "形容词",
       "zh": "他们的，她们的，它们的",
       "pos": "adj.poss.",
       "fr": "leur, leurs"
      },
      {
       "g": "形容词",
       "zh": "黑的，黑色的",
       "pos": "adj.",
       "fr": "noir(e)"
      },
      {
       "g": "形容词",
       "zh": "矮小的",
       "pos": "adj.",
       "fr": "petit(e)"
      },
      {
       "g": "形容词",
       "zh": "红色的",
       "pos": "adj.",
       "fr": "rouge"
      },
      {
       "g": "形容词",
       "zh": "青的，绿色的",
       "pos": "adj.",
       "fr": "vert(e)"
      },
      {
       "g": "代词",
       "zh": "他（用作主语或宾语的同位语，表示加强语气）",
       "pos": "pron.pers.",
       "fr": "lui"
      },
      {
       "g": "副词",
       "zh": "同意，赞同",
       "pos": "loc.adv.",
       "fr": "d'accord"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "不；没有",
       "pos": "",
       "fr": "ne… pas"
      }
     ],
     "cloze": [
      [
       "– Alors… Ils sont ",
       {
        "b": "grands"
       },
       " ? petits ?"
      ],
      [
       "– Il y a un ",
       {
        "b": "homme"
       },
       ", grand et… ",
       {
        "b": "blond"
       },
       ". Oui, c'est ça, il ",
       {
        "b": "est"
       },
       " blond. L'",
       {
        "b": "autre"
       },
       " homme, il ",
       {
        "b": "est"
       },
       " petit et ",
       {
        "b": "brun"
       },
       "."
      ],
      [
       "– D'accord. Est-ce qu'",
       {
        "b": "ils"
       },
       " ont ",
       {
        "b": "des"
       },
       " lunettes ?"
      ],
      [
       "– Non, ",
       {
        "b": "non"
       },
       ", ils n'",
       {
        "b": "ont"
       },
       " pas de ",
       {
        "b": "lunettes"
       },
       "."
      ],
      [
       "– Et leurs ",
       {
        "b": "vêtements"
       },
       " ?"
      ],
      [
       "– L'homme ",
       {
        "b": "blond"
       },
       " porte un ",
       {
        "b": "tee"
       },
       "-shirt ",
       {
        "b": "blanc"
       },
       " et un pantalon ",
       {
        "b": "noir"
       },
       "… Non, bleu, un ",
       {
        "b": "pantalon"
       },
       " bleu. C'",
       {
        "b": "est"
       },
       " un jean. L'",
       {
        "b": "homme"
       },
       " brun, ",
       {
        "b": "lui"
       },
       ", il a un blouson."
      ],
      [
       "– De ",
       {
        "b": "quelle"
       },
       " couleur ?"
      ],
      [
       "– La ",
       {
        "b": "couleur"
       },
       " de son ",
       {
        "b": "blouson"
       },
       "… noir… ",
       {
        "b": "non"
       },
       ", ce n'est ",
       {
        "b": "pas"
       },
       " noir… ",
       {
        "b": "rouge"
       },
       "… oui, ",
       {
        "b": "rouge"
       },
       "."
      ],
      [
       "– Autre chose ?"
      ],
      [
       "– Oui, sa ",
       {
        "b": "chemise"
       },
       " est ",
       {
        "b": "verte"
       },
       "."
      ],
      [
       "– Et ses ",
       {
        "b": "chaussures"
       },
       " ?"
      ],
      [
       "– Ah ! ce sont ",
       {
        "b": "des"
       },
       " baskets."
      ]
     ],
     "text": [
      {
       "zh": "– 那么……他们个子高吗？矮吗？",
       "fr": "– Alors… Ils sont grands ? petits ?"
      },
      {
       "zh": "– 有一个男人，个子高，而且……是金发。对，没错，他是金发。另一个男人，个子矮，是棕发。",
       "fr": "– Il y a un homme, grand et… blond. Oui, c'est ça, il est blond. L'autre homme, il est petit et brun."
      },
      {
       "zh": "– 好的。他们戴眼镜吗？",
       "fr": "– D'accord. Est-ce qu'ils ont des lunettes ?"
      },
      {
       "zh": "– 不，不，他们不戴眼镜。",
       "fr": "– Non, non, ils n'ont pas de lunettes."
      },
      {
       "zh": "– 那他们的衣服呢？",
       "fr": "– Et leurs vêtements ?"
      },
      {
       "zh": "– 金发男人穿一件白色 T 恤和一条黑色长裤……不，是蓝色，一条蓝色长裤。是牛仔裤。棕发男人呢，他有一件夹克衫。",
       "fr": "– L'homme blond porte un tee-shirt blanc et un pantalon noir… Non, bleu, un pantalon bleu. C'est un jean. L'homme brun, lui, il a un blouson."
      },
      {
       "zh": "– 什么颜色的？",
       "fr": "– De quelle couleur ?"
      },
      {
       "zh": "– 他夹克衫的颜色……黑色……不，不是黑色……红色……对，红色。",
       "fr": "– La couleur de son blouson… noir… non, ce n'est pas noir… rouge… oui, rouge."
      },
      {
       "zh": "– 还有别的吗？",
       "fr": "– Autre chose ?"
      },
      {
       "zh": "– 有，他的衬衫是绿色的。",
       "fr": "– Oui, sa chemise est verte."
      },
      {
       "zh": "– 那他的鞋呢？",
       "fr": "– Et ses chaussures ?"
      },
      {
       "zh": "– 啊！是运动鞋。",
       "fr": "– Ah ! ce sont des baskets."
      }
     ]
    },
    {
     "n": 7,
     "title": "Shopping",
     "zh": "购物",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "欧元",
       "pos": "n.m.",
       "fr": "euro"
      },
      {
       "g": "阳性名词",
       "zh": "〈俗〉羊毛套衫（pull-over的缩写）",
       "pos": "n.m.",
       "fr": "pull"
      },
      {
       "g": "阳性名词",
       "zh": "在商店购物",
       "pos": "n.m.",
       "fr": "shopping"
      },
      {
       "g": "阳性名词",
       "zh": "类型，型；种",
       "pos": "n.m.",
       "fr": "type"
      },
      {
       "g": "阴性名词",
       "zh": "（女用）长外衣，连衣裙",
       "pos": "n.f.",
       "fr": "robe"
      },
      {
       "g": "阴性名词",
       "zh": "（成衣的）尺码，号码",
       "pos": "n.f.",
       "fr": "taille"
      },
      {
       "g": "动词",
       "zh": "价值(多少钱)；花费，花钱",
       "pos": "v.i.",
       "fr": "coûter"
      },
      {
       "g": "动词",
       "zh": "〈俗〉价值（价格）为……；尺寸为……；容量为……",
       "pos": "v.t.",
       "fr": "faire"
      },
      {
       "g": "动词",
       "zh": "感到，觉得，认为，以为",
       "pos": "v.t.",
       "fr": "trouver"
      },
      {
       "g": "形容词",
       "zh": "[用作感叹词，表示赞成或不满、惊奇、厌恶等]",
       "pos": "adj.",
       "fr": "bon(ne)"
      },
      {
       "g": "形容词",
       "zh": "高价的，昂贵的",
       "pos": "adj.",
       "fr": "cher(ère)"
      },
      {
       "g": "形容词",
       "zh": "灰色的",
       "pos": "adj.",
       "fr": "gris(e)"
      },
      {
       "g": "形容词",
       "zh": "漂亮的，好看的",
       "pos": "adj.",
       "fr": "joli(e)"
      },
      {
       "g": "副词",
       "zh": "许多，很，非常，完全，十分",
       "pos": "adv.",
       "fr": "bien"
      },
      {
       "g": "副词",
       "zh": "多少（用于疑问句中）",
       "pos": "adv.interr.",
       "fr": "combien"
      },
      {
       "g": "副词",
       "zh": "很，极，非常",
       "pos": "adv.",
       "fr": "très"
      },
      {
       "g": "介词、连词",
       "zh": "（表示数量的相加）加，又",
       "pos": "conj.",
       "fr": "et"
      },
      {
       "g": "介词、连词",
       "zh": "对于，适合于（表示对象、用途）",
       "pos": "prép.",
       "fr": "pour"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "嗯！（表示怀疑、不耐烦或持保留意见）",
       "pos": "interj.",
       "fr": "*hum"
      }
     ],
     "cloze": [
      [
       "对话 1"
      ],
      [
       "– Bonjour, mesdames, qu'",
       {
        "b": "est"
       },
       "-ce que ",
       {
        "b": "vous"
       },
       " cherchez ?"
      ],
      [
       "– Des ",
       {
        "b": "vêtements"
       },
       " pour ma ",
       {
        "b": "fille"
       },
       " et mon ",
       {
        "b": "fils"
       },
       "."
      ],
      [
       "– Quel âge ",
       {
        "b": "ont"
       },
       "-ils ?"
      ],
      [
       "– Ma ",
       {
        "b": "fille"
       },
       " a 16 ans et ",
       {
        "b": "mon"
       },
       " fils 14."
      ],
      [
       "– Pour ",
       {
        "b": "les"
       },
       " filles, c'",
       {
        "b": "est"
       },
       " sur ",
       {
        "b": "les"
       },
       " étagères à ",
       {
        "b": "gauche"
       },
       " et pour ",
       {
        "b": "les"
       },
       " garçons, à ",
       {
        "b": "droite"
       },
       "."
      ],
      [
       "对话 2"
      ],
      [
       "– Comment est-ce ",
       {
        "b": "que"
       },
       " tu trouves ce ",
       {
        "b": "pantalon"
       },
       " ?"
      ],
      [
       "– J'aime ",
       {
        "b": "bien"
       },
       " ce type de ",
       {
        "b": "pantalon"
       },
       ", c'est ",
       {
        "b": "très"
       },
       " joli !"
      ],
      [
       "– Vous ",
       {
        "b": "avez"
       },
       " quelles ",
       {
        "b": "couleurs"
       },
       ", s'il vous ",
       {
        "b": "plaît"
       },
       " ?"
      ],
      [
       "– Ce pantalon ? Il y a ",
       {
        "b": "bleu"
       },
       ", gris ou ",
       {
        "b": "noir"
       },
       "."
      ],
      [
       "– Il coûte ",
       {
        "b": "combien"
       },
       " ?"
      ],
      [
       "– 59 euros."
      ],
      [
       "– Ce n'",
       {
        "b": "est"
       },
       " pas ",
       {
        "b": "très"
       },
       " cher !"
      ],
      [
       "– Hum, ",
       {
        "b": "hum"
       },
       ". Pas très ",
       {
        "b": "cher"
       },
       "…"
      ],
      [
       "– Vous avez le ",
       {
        "b": "gris"
       },
       " en taille 38 ?"
      ],
      [
       "– Oui, ",
       {
        "b": "oui"
       },
       "."
      ],
      [
       "– Cette robe ",
       {
        "b": "verte"
       },
       ", tu aimes ?"
      ],
      [
       "对话 3"
      ],
      [
       "– Oh, ",
       {
        "b": "non"
       },
       " ! Pas du tout."
      ],
      [
       "– Ah ",
       {
        "b": "bon"
       },
       " ! Et ce pull ? Il ",
       {
        "b": "est"
       },
       " joli, ",
       {
        "b": "non"
       },
       " ?"
      ],
      [
       "– Oui, le bleu et ",
       {
        "b": "blanc"
       },
       ", j'aime ",
       {
        "b": "bien"
       },
       "."
      ],
      [
       "– Combien ça coûte ?"
      ],
      [
       "– 35 ",
       {
        "b": "euros"
       },
       "."
      ],
      [
       "– Bon, alors… Ce ",
       {
        "b": "pull"
       },
       " et ce pantalon, ça ",
       {
        "b": "fait"
       },
       " combien, s'il ",
       {
        "b": "vous"
       },
       " plaît ?"
      ],
      [
       "– 35 et 59… ça ",
       {
        "b": "fait"
       },
       " 94 euros, ",
       {
        "b": "madame"
       },
       "."
      ],
      [
       "– Voilà."
      ]
     ],
     "text": [
      {
       "h": "对话 1"
      },
      {
       "zh": "– 您好，女士们，你们在找什么？",
       "fr": "– Bonjour, mesdames, qu'est-ce que vous cherchez ?"
      },
      {
       "zh": "– 给我女儿和儿子的衣服。",
       "fr": "– Des vêtements pour ma fille et mon fils."
      },
      {
       "zh": "– 他们多大了？",
       "fr": "– Quel âge ont-ils ?"
      },
      {
       "zh": "– 我女儿16岁，儿子14岁。",
       "fr": "– Ma fille a 16 ans et mon fils 14."
      },
      {
       "zh": "– 女孩的在左边的架子上，男孩的在右边。",
       "fr": "– Pour les filles, c'est sur les étagères à gauche et pour les garçons, à droite."
      },
      {
       "h": "对话 2"
      },
      {
       "zh": "– 你觉得这条裤子怎么样？",
       "fr": "– Comment est-ce que tu trouves ce pantalon ?"
      },
      {
       "zh": "– 我挺喜欢这种款式的裤子，很漂亮！",
       "fr": "– J'aime bien ce type de pantalon, c'est très joli !"
      },
      {
       "zh": "– 请问，你们有哪些颜色？",
       "fr": "– Vous avez quelles couleurs, s'il vous plaît ?"
      },
      {
       "zh": "– 这条裤子吗？有蓝色、灰色或黑色。",
       "fr": "– Ce pantalon ? Il y a bleu, gris ou noir."
      },
      {
       "zh": "– 多少钱？",
       "fr": "– Il coûte combien ?"
      },
      {
       "zh": "– 59 欧元。",
       "fr": "– 59 euros."
      },
      {
       "zh": "– 不算太贵！",
       "fr": "– Ce n'est pas très cher !"
      },
      {
       "zh": "– 嗯，嗯。不太贵……",
       "fr": "– Hum, hum. Pas très cher…"
      },
      {
       "zh": "– 你们有38号的灰色吗？",
       "fr": "– Vous avez le gris en taille 38 ?"
      },
      {
       "zh": "– 有，有。",
       "fr": "– Oui, oui."
      },
      {
       "zh": "– 这条绿色的裙子，你喜欢吗？",
       "fr": "– Cette robe verte, tu aimes ?"
      },
      {
       "h": "对话 3"
      },
      {
       "zh": "– 哦，不！一点也不喜欢。",
       "fr": "– Oh, non ! Pas du tout."
      },
      {
       "zh": "– 啊，是吗！那这件毛衣呢？很漂亮，不是吗？",
       "fr": "– Ah bon ! Et ce pull ? Il est joli, non ?"
      },
      {
       "zh": "– 是的，蓝白相间的，我挺喜欢。",
       "fr": "– Oui, le bleu et blanc, j'aime bien."
      },
      {
       "zh": "– 多少钱？",
       "fr": "– Combien ça coûte ?"
      },
      {
       "zh": "– 35 欧元。",
       "fr": "– 35 euros."
      },
      {
       "zh": "– 好，那么……这件毛衣和这条裤子，一共多少钱？",
       "fr": "– Bon, alors… Ce pull et ce pantalon, ça fait combien, s'il vous plaît ?"
      },
      {
       "zh": "– 35加59……一共94欧元，女士。",
       "fr": "– 35 et 59… ça fait 94 euros, madame."
      },
      {
       "zh": "– 给您。",
       "fr": "– Voilà."
      }
     ]
    },
    {
     "n": 8,
     "title": "Le coin des artistes",
     "zh": "艺术家之角",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "角，角落；街角处",
       "pos": "n.m.",
       "fr": "coin"
      },
      {
       "g": "阳性名词",
       "zh": "作家",
       "pos": "n.m.",
       "fr": "écrivain"
      },
      {
       "g": "阳性名词",
       "zh": "电影，影片",
       "pos": "n.m.",
       "fr": "film"
      },
      {
       "g": "阳性名词",
       "zh": "诗歌",
       "pos": "n.m.",
       "fr": "poème"
      },
      {
       "g": "阳性名词",
       "zh": "诗人",
       "pos": "n.m.",
       "fr": "poète"
      },
      {
       "g": "阳性名词",
       "zh": "画",
       "pos": "n.m.",
       "fr": "tableau¹"
      },
      {
       "g": "阳性名词",
       "zh": "表，表格",
       "pos": "n.m.",
       "fr": "tableau²"
      },
      {
       "g": "阳性名词",
       "zh": "地毯",
       "pos": "n.m.",
       "fr": "tapis"
      },
      {
       "g": "阴性名词",
       "zh": "柑，橘，橙",
       "pos": "n.f.",
       "fr": "orange"
      },
      {
       "g": "名词",
       "zh": "艺术家",
       "pos": "n.",
       "fr": "artiste"
      },
      {
       "g": "名词",
       "zh": "〈俗〉小孩，小家伙",
       "pos": "n.",
       "fr": "môme"
      },
      {
       "g": "名词",
       "zh": "音乐家，作曲家，演奏家",
       "pos": "n.",
       "fr": "musicien(ne)"
      },
      {
       "g": "名词",
       "zh": "画家，画师",
       "pos": "n.",
       "fr": "peintre"
      },
      {
       "g": "名词",
       "zh": "雕刻家，雕塑家",
       "pos": "n.",
       "fr": "sculpteur(trice)"
      },
      {
       "g": "介词、连词",
       "zh": "在……之间（常与et连用，表示时间或空间）",
       "pos": "prép.",
       "fr": "entre"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "[介词de和定冠词les的缩合形式]",
       "pos": "art.contr.",
       "fr": "des"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "[介词de和定冠词le的缩合形式]",
       "pos": "art.contr.",
       "fr": "du"
      }
     ],
     "cloze": [
      [
       "电影 La Môme"
      ],
      [
       "La Môme, un film d'Olivier Dahan. Avec Marion Cotillard, Gérard Depardieu…"
      ],
      [
       "看图说话"
      ],
      [
       "Le ",
       {
        "b": "poète"
       },
       " est ",
       {
        "b": "entre"
       },
       " Henri Matisse et Camille Claudel."
      ],
      [
       "Claude Debussy est à ",
       {
        "b": "droite"
       },
       " dans le ",
       {
        "b": "tableau"
       },
       "."
      ],
      [
       "Le sculpteur ",
       {
        "b": "est"
       },
       " une ",
       {
        "b": "femme"
       },
       "."
      ],
      [
       "Colette est à ",
       {
        "b": "gauche"
       },
       " du peintre."
      ],
      [
       "Le ",
       {
        "b": "poète"
       },
       " est à ",
       {
        "b": "gauche"
       },
       " du sculpteur et à ",
       {
        "b": "droite"
       },
       " du peintre."
      ],
      [
       "À ",
       {
        "b": "côté"
       },
       " de Claude Debussy, il y a le sculpteur."
      ],
      [
       "Le ",
       {
        "b": "peintre"
       },
       " est à ",
       {
        "b": "côté"
       },
       " de l'écrivain."
      ],
      [
       "L'",
       {
        "b": "écrivain"
       },
       " est à ",
       {
        "b": "gauche"
       },
       " dans le ",
       {
        "b": "tableau"
       },
       "."
      ],
      [
       "Guillaume Apollinaire n'est ",
       {
        "b": "pas"
       },
       " le musicien."
      ]
     ],
     "text": [
      {
       "h": "电影 La Môme"
      },
      {
       "zh": "La Môme，Olivier Dahan 的一部电影。主演：Marion Cotillard、Gérard Depardieu……",
       "fr": "La Môme, un film d'Olivier Dahan. Avec Marion Cotillard, Gérard Depardieu…"
      },
      {
       "h": "看图说话"
      },
      {
       "zh": "诗人在 Henri Matisse 和 Camille Claudel 之间。",
       "fr": "Le poète est entre Henri Matisse et Camille Claudel."
      },
      {
       "zh": "Claude Debussy 在画中的右边。",
       "fr": "Claude Debussy est à droite dans le tableau."
      },
      {
       "zh": "雕塑家是一位女性。",
       "fr": "Le sculpteur est une femme."
      },
      {
       "zh": "Colette 在画家的左边。",
       "fr": "Colette est à gauche du peintre."
      },
      {
       "zh": "诗人在雕塑家的左边、画家的右边。",
       "fr": "Le poète est à gauche du sculpteur et à droite du peintre."
      },
      {
       "zh": "在 Claude Debussy 旁边，有雕塑家。",
       "fr": "À côté de Claude Debussy, il y a le sculpteur."
      },
      {
       "zh": "画家在作家旁边。",
       "fr": "Le peintre est à côté de l'écrivain."
      },
      {
       "zh": "作家在画中的左边。",
       "fr": "L'écrivain est à gauche dans le tableau."
      },
      {
       "zh": "Guillaume Apollinaire 不是音乐家。",
       "fr": "Guillaume Apollinaire n'est pas le musicien."
      }
     ]
    }
   ]
  },
  {
   "n": 3,
   "lecons": [
    {
     "n": 9,
     "title": "Appartement à louer",
     "zh": "待租公寓",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "公寓套房",
       "pos": "n.m.",
       "fr": "appartement"
      },
      {
       "g": "阳性名词",
       "zh": "末端，尽头",
       "pos": "n.m.",
       "fr": "bout"
      },
      {
       "g": "阳性名词",
       "zh": "办公桌，写字台；办公室",
       "pos": "n.m.",
       "fr": "bureau"
      },
      {
       "g": "阳性名词",
       "zh": "走廊",
       "pos": "n.m.",
       "fr": "couloir"
      },
      {
       "g": "阳性名词",
       "zh": "楼层",
       "pos": "n.m.",
       "fr": "étage"
      },
      {
       "g": "阳性名词",
       "zh": "房屋，大楼",
       "pos": "n.m.",
       "fr": "immeuble"
      },
      {
       "g": "阳性名词",
       "zh": "米",
       "pos": "n.m.",
       "fr": "mètre"
      },
      {
       "g": "阳性名词",
       "zh": "平方米",
       "pos": "n.m.",
       "fr": "mètre carré"
      },
      {
       "g": "阳性名词",
       "zh": "月，月份",
       "pos": "n.m.",
       "fr": "mois"
      },
      {
       "g": "阳性名词",
       "zh": "停车场",
       "pos": "n.m.",
       "fr": "parking"
      },
      {
       "g": "阳性名词",
       "zh": "壁橱",
       "pos": "n.m.",
       "fr": "placard"
      },
      {
       "g": "阳性名词",
       "zh": "平面图",
       "pos": "n.m.",
       "fr": "plan"
      },
      {
       "g": "阳性名词",
       "zh": "（建筑物的）底层，一楼",
       "pos": "n.m.",
       "fr": "rez-de-chaussée"
      },
      {
       "g": "阴性名词",
       "zh": "代理处，代办处",
       "pos": "n.f.",
       "fr": "agence"
      },
      {
       "g": "阴性名词",
       "zh": "房产代理公司",
       "pos": "n.f.",
       "fr": "agence immobilière"
      },
      {
       "g": "阴性名词",
       "zh": "启事，告示，布告，公告",
       "pos": "n.f.",
       "fr": "annonce"
      },
      {
       "g": "阴性名词",
       "zh": "（报纸上的）启事（栏），广告（栏）",
       "pos": "n.f.",
       "fr": "petite annonce"
      },
      {
       "g": "阴性名词",
       "zh": "（城市中通常栽有树木的）大街",
       "pos": "n.f.",
       "fr": "avenue"
      },
      {
       "g": "阴性名词",
       "zh": "厨房；烹调，烹饪法；菜肴",
       "pos": "n.f.",
       "fr": "cuisine"
      },
      {
       "g": "阴性名词",
       "zh": "淋浴；淋浴设备，莲蓬头",
       "pos": "n.f.",
       "fr": "douche"
      },
      {
       "g": "阴性名词",
       "zh": "入口；门厅",
       "pos": "n.f.",
       "fr": "entrée"
      },
      {
       "g": "阴性名词",
       "zh": "（物体的）面",
       "pos": "n.f.",
       "fr": "face"
      },
      {
       "g": "阴性名词",
       "zh": "房间，室",
       "pos": "n.f.",
       "fr": "salle"
      },
      {
       "g": "阴性名词",
       "zh": "浴室",
       "pos": "n.f.",
       "fr": "salle de bains"
      },
      {
       "g": "阴性名词",
       "zh": "卫生间，厕所",
       "pos": "n.f.pl.",
       "fr": "toilettes"
      },
      {
       "g": "名词",
       "zh": "负责人",
       "pos": "n.",
       "fr": "responsable"
      },
      {
       "g": "动词",
       "zh": "出租；租用",
       "pos": "v.t.",
       "fr": "louer"
      },
      {
       "g": "形容词",
       "zh": "旧的，先前的",
       "pos": "adj.",
       "fr": "ancien(ne)"
      },
      {
       "g": "形容词",
       "zh": "吵闹的",
       "pos": "adj.",
       "fr": "bruyant(e)"
      },
      {
       "g": "形容词",
       "zh": "明亮的；清晰的，清楚的",
       "pos": "adj.",
       "fr": "clair(e)"
      },
      {
       "g": "形容词",
       "zh": "不动产的",
       "pos": "adj.",
       "fr": "immobilier(ère)"
      },
      {
       "g": "形容词",
       "zh": "第一的",
       "pos": "adj.",
       "fr": "premier(ère)"
      },
      {
       "g": "形容词",
       "zh": "最近的，新近的",
       "pos": "adj.",
       "fr": "récent(e)"
      },
      {
       "g": "形容词",
       "zh": "昏暗的，阴暗的",
       "pos": "adj.",
       "fr": "sombre"
      },
      {
       "g": "形容词",
       "zh": "第三的",
       "pos": "adj.num.ord.",
       "fr": "troisième"
      },
      {
       "g": "副词",
       "zh": "在哪儿，去哪里",
       "pos": "adv.interr.",
       "fr": "où"
      },
      {
       "g": "介词、连词",
       "zh": "在……家；在……那里",
       "pos": "prép.",
       "fr": "chez"
      }
     ],
     "cloze": [
      [
       "电子邮件"
      ],
      [
       "Monsieur,"
      ],
      [
       "L'immeuble ",
       {
        "b": "est"
       },
       " au coin de la ",
       {
        "b": "rue"
       },
       " Victor-Hugo et de la rue Michelet. C'",
       {
        "b": "est"
       },
       " un immeuble ",
       {
        "b": "récent"
       },
       " avec un ",
       {
        "b": "parking"
       },
       ". L'appartement ",
       {
        "b": "est"
       },
       " au troisième ",
       {
        "b": "étage"
       },
       " avec ",
       {
        "b": "ascenseur"
       },
       "."
      ],
      [
       "La cuisine ",
       {
        "b": "est"
       },
       " à gauche de l'",
       {
        "b": "entrée"
       },
       "."
      ],
      [
       "En face de la ",
       {
        "b": "cuisine"
       },
       ", vous ",
       {
        "b": "avez"
       },
       " les ",
       {
        "b": "toilettes"
       },
       " et une ",
       {
        "b": "salle"
       },
       " de bains ",
       {
        "b": "avec"
       },
       " une ",
       {
        "b": "douche"
       },
       ". La chambre ",
       {
        "b": "est"
       },
       " au bout du ",
       {
        "b": "couloir"
       },
       ", à droite : il y a un ",
       {
        "b": "lit"
       },
       " et un bureau ",
       {
        "b": "avec"
       },
       " une ",
       {
        "b": "chaise"
       },
       "."
      ],
      [
       "À gauche du ",
       {
        "b": "couloir"
       },
       ", il y a le salon. C'",
       {
        "b": "est"
       },
       " calme."
      ],
      [
       "Vous ",
       {
        "b": "avez"
       },
       " deux ",
       {
        "b": "placards"
       },
       " dans l'",
       {
        "b": "appartement"
       },
       "."
      ],
      [
       "Meilleures salutations."
      ],
      [
       "Alain Dauger"
      ],
      [
       "Responsable de l'",
       {
        "b": "agence"
       },
       " Loca-loisirs"
      ]
     ],
     "text": [
      {
       "h": "电子邮件"
      },
      {
       "zh": "先生：",
       "fr": "Monsieur,"
      },
      {
       "zh": "大楼在 Victor-Hugo 街和 Michelet 街的拐角处。这是一栋新楼，带停车场。公寓在第三层（中式四楼），有电梯。",
       "fr": "L'immeuble est au coin de la rue Victor-Hugo et de la rue Michelet. C'est un immeuble récent avec un parking. L'appartement est au troisième étage avec ascenseur."
      },
      {
       "zh": "厨房在入口的左边。",
       "fr": "La cuisine est à gauche de l'entrée."
      },
      {
       "zh": "在厨房对面，有卫生间和一间带淋浴的浴室。卧室在走廊尽头，在右边：有一张床，还有一张带椅子的书桌。",
       "fr": "En face de la cuisine, vous avez les toilettes et une salle de bains avec une douche. La chambre est au bout du couloir, à droite : il y a un lit et un bureau avec une chaise."
      },
      {
       "zh": "走廊的左边是客厅。很安静。",
       "fr": "À gauche du couloir, il y a le salon. C'est calme."
      },
      {
       "zh": "公寓里有两个壁橱。",
       "fr": "Vous avez deux placards dans l'appartement."
      },
      {
       "zh": "致以诚挚的问候。",
       "fr": "Meilleures salutations."
      },
      {
       "h": "Alain Dauger"
      },
      {
       "zh": "Loca-loisirs 中介公司的负责人",
       "fr": "Responsable de l'agence Loca-loisirs"
      }
     ]
    },
    {
     "n": 10,
     "title": "C'est par où ?",
     "zh": "从哪儿走",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "公交车",
       "pos": "n.m.",
       "fr": "bus"
      },
      {
       "g": "阳性名词",
       "zh": "公园，花园",
       "pos": "n.m.",
       "fr": "jardin"
      },
      {
       "g": "阳性名词",
       "zh": "地铁",
       "pos": "n.m.",
       "fr": "métro"
      },
      {
       "g": "阳性名词",
       "zh": "博物馆",
       "pos": "n.m.",
       "fr": "musée"
      },
      {
       "g": "阳性名词",
       "zh": "歌剧；歌剧院",
       "pos": "n.m.",
       "fr": "opéra"
      },
      {
       "g": "阳性名词",
       "zh": "原谅，饶恕，宽恕",
       "pos": "n.m.",
       "fr": "pardon"
      },
      {
       "g": "阳性名词",
       "zh": "脚，足",
       "pos": "n.m.",
       "fr": "pied"
      },
      {
       "g": "阳性名词",
       "zh": "桥",
       "pos": "n.m.",
       "fr": "pont"
      },
      {
       "g": "阳性名词",
       "zh": "轮滑鞋",
       "pos": "n.m.pl.",
       "fr": "rollers"
      },
      {
       "g": "阳性名词",
       "zh": "工作",
       "pos": "n.m.",
       "fr": "travail"
      },
      {
       "g": "阳性名词",
       "zh": "自行车",
       "pos": "n.m.",
       "fr": "vélo"
      },
      {
       "g": "阴性名词",
       "zh": "银行",
       "pos": "n.f.",
       "fr": "banque"
      },
      {
       "g": "阴性名词",
       "zh": "线；运输线路",
       "pos": "n.f.",
       "fr": "ligne"
      },
      {
       "g": "阴性名词",
       "zh": "摩托车",
       "pos": "n.f.",
       "fr": "moto"
      },
      {
       "g": "阴性名词",
       "zh": "广场",
       "pos": "n.f.",
       "fr": "place"
      },
      {
       "g": "阴性名词",
       "zh": "邮局",
       "pos": "n.f.",
       "fr": "poste"
      },
      {
       "g": "阴性名词",
       "zh": "汽车，小轿车",
       "pos": "n.f.",
       "fr": "voiture"
      },
      {
       "g": "动词",
       "zh": "继续（做）",
       "pos": "v.",
       "fr": "continuer"
      },
      {
       "g": "动词",
       "zh": "进入",
       "pos": "v.i.",
       "fr": "entrer"
      },
      {
       "g": "动词",
       "zh": "经过；递",
       "pos": "v.",
       "fr": "passer"
      },
      {
       "g": "动词",
       "zh": "搭乘；选取（道路，路线）；拿",
       "pos": "v.t.",
       "fr": "prendre"
      },
      {
       "g": "动词",
       "zh": "穿越，穿过",
       "pos": "v.t.",
       "fr": "traverser"
      },
      {
       "g": "形容词",
       "zh": "直的；直接的",
       "pos": "adj.",
       "fr": "direct(e)"
      },
      {
       "g": "副词",
       "zh": "然后",
       "pos": "adv.",
       "fr": "après"
      },
      {
       "g": "副词",
       "zh": "笔直地",
       "pos": "adv.",
       "fr": "droit"
      },
      {
       "g": "副词",
       "zh": "然后，接下来",
       "pos": "adv.",
       "fr": "ensuite"
      },
      {
       "g": "副词",
       "zh": "那儿，那里",
       "pos": "adv.",
       "fr": "là"
      },
      {
       "g": "副词",
       "zh": "远",
       "pos": "adv.",
       "fr": "loin"
      },
      {
       "g": "副词",
       "zh": "十分，非常，极其，完全",
       "pos": "adv.",
       "fr": "tout"
      },
      {
       "g": "介词、连词",
       "zh": "直到，直至（与介词连用，可以表示时间和空间限度）",
       "pos": "prép.",
       "fr": "jusque"
      },
      {
       "g": "介词、连词",
       "zh": "经过，通过，从（表示地点）",
       "pos": "prép.",
       "fr": "par"
      },
      {
       "g": "冠词、感叹词、短语",
       "zh": "当然（语气词）",
       "pos": "loc.",
       "fr": "bien sûr"
      }
     ],
     "cloze": [
      [
       "– Pardon, monsieur. Le ",
       {
        "b": "musée"
       },
       " du Louvre, c'est ",
       {
        "b": "par"
       },
       " où ?"
      ],
      [
       "– Oh ! là, là ! Vous êtes ",
       {
        "b": "loin"
       },
       ". Prenez le métro."
      ],
      [
       "– Je n'",
       {
        "b": "aime"
       },
       " pas le ",
       {
        "b": "métro"
       },
       "."
      ],
      [
       "– Alors, allez-y en ",
       {
        "b": "bus"
       },
       " ou à vélo : il y a ",
       {
        "b": "des"
       },
       " Vélib', au coin de la ",
       {
        "b": "rue"
       },
       "."
      ],
      [
       "– Non, non. J'y ",
       {
        "b": "vais"
       },
       " à pied."
      ],
      [
       "– Bien. Alors, ",
       {
        "b": "passez"
       },
       " par là. Traversez le ",
       {
        "b": "boulevard"
       },
       " Haussmann et prenez la ",
       {
        "b": "rue"
       },
       " Scribe en face de ",
       {
        "b": "vous"
       },
       ". Tournez à gauche ",
       {
        "b": "dans"
       },
       " la rue Auber. Passez ",
       {
        "b": "devant"
       },
       " la poste et la ",
       {
        "b": "banque"
       },
       " et vous ",
       {
        "b": "arrivez"
       },
       " place de l'Opéra. Ça va ?"
      ],
      [
       "– Oui, ",
       {
        "b": "oui"
       },
       "."
      ],
      [
       "– Ensuite, prenez la ",
       {
        "b": "grande"
       },
       " avenue en ",
       {
        "b": "face"
       },
       " et continuez ",
       {
        "b": "tout"
       },
       " droit, ",
       {
        "b": "jusqu"
       },
       "'au bout."
      ],
      [
       "– Hum, ",
       {
        "b": "hum"
       },
       "."
      ],
      [
       "– Et après, ",
       {
        "b": "traversez"
       },
       " la rue de Rivoli et ",
       {
        "b": "entrez"
       },
       " dans la ",
       {
        "b": "cour"
       },
       " du Louvre. À droite, ",
       {
        "b": "vous"
       },
       " avez le ",
       {
        "b": "jardin"
       },
       " des Tuileries et à ",
       {
        "b": "gauche"
       },
       " le Louvre. L'entrée du ",
       {
        "b": "musée"
       },
       " est ",
       {
        "b": "sous"
       },
       " la Pyramide."
      ],
      [
       "– Merci, euh… ",
       {
        "b": "les"
       },
       " Vélib', c'est où ?"
      ]
     ],
     "text": [
      {
       "zh": "– 打扰一下，先生。Louvre 博物馆怎么走？",
       "fr": "– Pardon, monsieur. Le musée du Louvre, c'est par où ?"
      },
      {
       "zh": "– 哎呀！您离得很远。坐地铁吧。",
       "fr": "– Oh ! là, là ! Vous êtes loin. Prenez le métro."
      },
      {
       "zh": "– 我不喜欢地铁。",
       "fr": "– Je n'aime pas le métro."
      },
      {
       "zh": "– 那么，坐公交车或者骑自行车去吧：街角有 Vélib'。",
       "fr": "– Alors, allez-y en bus ou à vélo : il y a des Vélib', au coin de la rue."
      },
      {
       "zh": "– 不，不。我步行去。",
       "fr": "– Non, non. J'y vais à pied."
      },
      {
       "zh": "– 好吧。那么，从那边走。穿过 Haussmann 大道，走您正对面的 Scribe 街。在 Auber 街向左拐。经过邮局和银行，您就到 Opéra 广场了。明白了吗？",
       "fr": "– Bien. Alors, passez par là. Traversez le boulevard Haussmann et prenez la rue Scribe en face de vous. Tournez à gauche dans la rue Auber. Passez devant la poste et la banque et vous arrivez place de l'Opéra. Ça va ?"
      },
      {
       "zh": "– 明白，明白。",
       "fr": "– Oui, oui."
      },
      {
       "zh": "– 然后，走对面的那条大街，一直往前走，直到尽头。",
       "fr": "– Ensuite, prenez la grande avenue en face et continuez tout droit, jusqu'au bout."
      },
      {
       "zh": "– 嗯，嗯。",
       "fr": "– Hum, hum."
      },
      {
       "zh": "– 再然后，穿过 Rivoli 街，进入 Louvre 的院子。右边是 Tuileries 花园，左边是 Louvre。博物馆的入口在 Pyramide 下面。",
       "fr": "– Et après, traversez la rue de Rivoli et entrez dans la cour du Louvre. À droite, vous avez le jardin des Tuileries et à gauche le Louvre. L'entrée du musée est sous la Pyramide."
      },
      {
       "zh": "– 谢谢，呃……Vélib' 在哪儿？",
       "fr": "– Merci, euh… les Vélib', c'est où ?"
      }
     ]
    },
    {
     "n": 11,
     "title": "Bon voyage !",
     "zh": "旅途愉快！",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "空气",
       "pos": "n.m.",
       "fr": "air"
      },
      {
       "g": "阳性名词",
       "zh": "空调",
       "pos": "n.m.",
       "fr": "air conditionné"
      },
      {
       "g": "阳性名词",
       "zh": "酒吧",
       "pos": "n.m.",
       "fr": "bar"
      },
      {
       "g": "阳性名词",
       "zh": "边，边缘；岸边",
       "pos": "n.m.",
       "fr": "bord"
      },
      {
       "g": "阳性名词",
       "zh": "旅游线路",
       "pos": "n.m.",
       "fr": "circuit"
      },
      {
       "g": "阳性名词",
       "zh": "建议",
       "pos": "n.m.",
       "fr": "conseil"
      },
      {
       "g": "阳性名词",
       "zh": "东，东边，东方",
       "pos": "n.m.",
       "fr": "est"
      },
      {
       "g": "阳性名词",
       "zh": "直升机",
       "pos": "n.m.",
       "fr": "hélicoptère"
      },
      {
       "g": "阳性名词",
       "zh": "日子，天",
       "pos": "n.m.",
       "fr": "jour"
      },
      {
       "g": "阳性名词",
       "zh": "北，北边，北方",
       "pos": "n.m.",
       "fr": "nord"
      },
      {
       "g": "阳性名词",
       "zh": "西，西边，西方",
       "pos": "n.m.",
       "fr": "ouest"
      },
      {
       "g": "阳性名词",
       "zh": "饭店（通俗语中简称为resto）",
       "pos": "n.m.",
       "fr": "restaurant"
      },
      {
       "g": "阳性名词",
       "zh": "南，南边，南方",
       "pos": "n.m.",
       "fr": "sud"
      },
      {
       "g": "阳性名词",
       "zh": "旅行；旅程，旅途",
       "pos": "n.m.",
       "fr": "voyage"
      },
      {
       "g": "阳性名词",
       "zh": "周末",
       "pos": "n.m.",
       "fr": "week-end"
      },
      {
       "g": "阴性名词",
       "zh": "地图",
       "pos": "n.f.",
       "fr": "carte"
      },
      {
       "g": "阴性名词",
       "zh": "岛",
       "pos": "n.f.",
       "fr": "île"
      },
      {
       "g": "阴性名词",
       "zh": "大海",
       "pos": "n.f.",
       "fr": "mer"
      },
      {
       "g": "阴性名词",
       "zh": "游泳池",
       "pos": "n.f.",
       "fr": "piscine"
      },
      {
       "g": "阴性名词",
       "zh": "沙滩",
       "pos": "n.f.",
       "fr": "plage"
      },
      {
       "g": "阴性名词",
       "zh": "接待处",
       "pos": "n.f.",
       "fr": "réception"
      },
      {
       "g": "阴性名词",
       "zh": "电视（系统）；〈俗〉电视机；电视行业（缩写形式为télé）",
       "pos": "n.f.",
       "fr": "télévision"
      },
      {
       "g": "阴性名词",
       "zh": "露台，晒台，大阳台；（咖啡馆、餐馆设在人行道上的）露天加座",
       "pos": "n.f.",
       "fr": "terrasse"
      },
      {
       "g": "阴性名词",
       "zh": "城市",
       "pos": "n.f.",
       "fr": "ville"
      },
      {
       "g": "阴性名词",
       "zh": "旅行社",
       "pos": "n.f.",
       "fr": "agence de voyages"
      },
      {
       "g": "动词",
       "zh": "出发，离开",
       "pos": "v.i.",
       "fr": "partir"
      },
      {
       "g": "动词",
       "zh": "参观，游览",
       "pos": "v.t.",
       "fr": "visiter"
      },
      {
       "g": "形容词",
       "zh": "好的，良好的；恰当的，正确的",
       "pos": "adj.",
       "fr": "bon(ne)"
      },
      {
       "g": "形容词",
       "zh": "有条件的，受条件限制的",
       "pos": "adj.",
       "fr": "conditionné(e)"
      },
      {
       "g": "形容词",
       "zh": "完美的",
       "pos": "adj.",
       "fr": "parfait(e)"
      },
      {
       "g": "代词",
       "zh": "我们；人，人们，大家，有人，别人，任何人",
       "pos": "pron.indéf.",
       "fr": "on"
      },
      {
       "g": "副词",
       "zh": "当然",
       "pos": "loc.adv.",
       "fr": "bien sûr"
      },
      {
       "g": "副词",
       "zh": "正好，恰巧",
       "pos": "adv.",
       "fr": "juste"
      },
      {
       "g": "副词",
       "zh": "然后",
       "pos": "adv.",
       "fr": "puis"
      }
     ],
     "cloze": [
      [
       "– Bien, alors, le ",
       {
        "b": "premier"
       },
       " jour, ",
       {
        "b": "vous"
       },
       " partez de Paris et ",
       {
        "b": "vous"
       },
       " arrivez à l'",
       {
        "b": "aéroport"
       },
       " de Fort-de-France. Là, vous ",
       {
        "b": "prenez"
       },
       " un bus ",
       {
        "b": "jusqu"
       },
       "'à votre ",
       {
        "b": "hôtel"
       },
       ", La Marina, à l'ouest de l'",
       {
        "b": "île"
       },
       "."
      ],
      [
       "– On est au ",
       {
        "b": "bord"
       },
       " de la mer ?"
      ],
      [
       "– Oui, c'",
       {
        "b": "est"
       },
       " un hôtel à ",
       {
        "b": "côté"
       },
       " de la plage. Votre ",
       {
        "b": "chambre"
       },
       " a une ",
       {
        "b": "terrasse"
       },
       " en face de la ",
       {
        "b": "mer"
       },
       "."
      ],
      [
       "– Et il y a une ",
       {
        "b": "salle"
       },
       " de bains ",
       {
        "b": "dans"
       },
       " la chambre ?"
      ],
      [
       "– Oui, ",
       {
        "b": "bien"
       },
       " sûr, ",
       {
        "b": "monsieur"
       },
       " : une ",
       {
        "b": "salle"
       },
       " de bains, le ",
       {
        "b": "téléphone"
       },
       ", la télévision et l'",
       {
        "b": "air"
       },
       " conditionné. Et, ",
       {
        "b": "dans"
       },
       " l'hôtel, ",
       {
        "b": "vous"
       },
       " avez ",
       {
        "b": "deux"
       },
       " bars, ",
       {
        "b": "deux"
       },
       " restaurants, ",
       {
        "b": "des"
       },
       " boutiques et ",
       {
        "b": "une"
       },
       " piscine."
      ],
      [
       "– Ah ! C'",
       {
        "b": "est"
       },
       " parfait ! Et on ",
       {
        "b": "visite"
       },
       " l'île ",
       {
        "b": "aussi"
       },
       " ?"
      ],
      [
       "– Oui, en hélicoptère. Vous ",
       {
        "b": "allez"
       },
       " aussi en ",
       {
        "b": "bus"
       },
       " à Fort-de-France et à Sainte-Luce au sud, à la ",
       {
        "b": "montagne"
       },
       " Pelée et à Saint-Pierre, au nord… Ah ! ",
       {
        "b": "bien"
       },
       " sûr, ",
       {
        "b": "visitez"
       },
       " le musée Gauguin, à ",
       {
        "b": "côté"
       },
       " de votre ",
       {
        "b": "hôtel"
       },
       ". C'est ",
       {
        "b": "très"
       },
       " sympa !"
      ]
     ],
     "text": [
      {
       "zh": "– 好，那么，第一天，您从 Paris 出发，到达 Fort-de-France 机场。到了那里，您坐公交车去您的酒店 La Marina，在岛的西边。",
       "fr": "– Bien, alors, le premier jour, vous partez de Paris et vous arrivez à l'aéroport de Fort-de-France. Là, vous prenez un bus jusqu'à votre hôtel, La Marina, à l'ouest de l'île."
      },
      {
       "zh": "– 我们在海边吗？",
       "fr": "– On est au bord de la mer ?"
      },
      {
       "zh": "– 是的，酒店就在海滩旁边。您的房间有一个面朝大海的露台。",
       "fr": "– Oui, c'est un hôtel à côté de la plage. Votre chambre a une terrasse en face de la mer."
      },
      {
       "zh": "– 房间里有浴室吗？",
       "fr": "– Et il y a une salle de bains dans la chambre ?"
      },
      {
       "zh": "– 当然有，先生：有浴室、电话、电视和空调。而且，酒店里有两个酒吧、两家餐厅、几家商店和一个游泳池。",
       "fr": "– Oui, bien sûr, monsieur : une salle de bains, le téléphone, la télévision et l'air conditionné. Et, dans l'hôtel, vous avez deux bars, deux restaurants, des boutiques et une piscine."
      },
      {
       "zh": "– 啊！太完美了！我们也参观这个岛吗？",
       "fr": "– Ah ! C'est parfait ! Et on visite l'île aussi ?"
      },
      {
       "zh": "– 是的，乘直升机。您还会坐公交车去 Fort-de-France 和南边的 Sainte-Luce，去 Pelée 山，以及北边的 Saint-Pierre……啊！当然，还要参观 Gauguin 博物馆，就在您的酒店旁边。很不错！",
       "fr": "– Oui, en hélicoptère. Vous allez aussi en bus à Fort-de-France et à Sainte-Luce au sud, à la montagne Pelée et à Saint-Pierre, au nord… Ah ! bien sûr, visitez le musée Gauguin, à côté de votre hôtel. C'est très sympa !"
      }
     ]
    },
    {
     "n": 12,
     "title": "Marseille",
     "zh": "马赛",
     "vocab": [
      {
       "g": "阳性名词",
       "zh": "飞机场",
       "pos": "n.m.",
       "fr": "aéroport"
      },
      {
       "g": "阳性名词",
       "zh": "水族馆",
       "pos": "n.m.",
       "fr": "aquarium"
      },
      {
       "g": "阳性名词",
       "zh": "艺术；美术",
       "pos": "n.m.",
       "fr": "art"
      },
      {
       "g": "阳性名词",
       "zh": "飞机",
       "pos": "n.m.",
       "fr": "avion"
      },
      {
       "g": "阳性名词",
       "zh": "船",
       "pos": "n.m.",
       "fr": "bateau"
      },
      {
       "g": "阳性名词",
       "zh": "票",
       "pos": "n.m.",
       "fr": "billet"
      },
      {
       "g": "阳性名词",
       "zh": "中心；中部",
       "pos": "n.m.",
       "fr": "centre"
      },
      {
       "g": "阳性名词",
       "zh": "城堡",
       "pos": "n.m.",
       "fr": "château"
      },
      {
       "g": "阳性名词",
       "zh": "宾馆，大饭店；(行政机关)办公大楼，官邸，大厦",
       "pos": "n.m.",
       "fr": "hôtel"
      },
      {
       "g": "阳性名词",
       "zh": "市政府大楼",
       "pos": "n.m.",
       "fr": "hôtel de ville"
      },
      {
       "g": "阳性名词",
       "zh": "千米",
       "pos": "n.m.",
       "fr": "kilomètre"
      },
      {
       "g": "阳性名词",
       "zh": "事务所，营业所",
       "pos": "n.m.",
       "fr": "office"
      },
      {
       "g": "阳性名词",
       "zh": "宫殿，王宫；高大华丽的建筑物",
       "pos": "n.m.",
       "fr": "palais"
      },
      {
       "g": "阳性名词",
       "zh": "港口",
       "pos": "n.m.",
       "fr": "port"
      },
      {
       "g": "阳性名词",
       "zh": "站台；堤岸",
       "pos": "n.m.",
       "fr": "quai"
      },
      {
       "g": "阳性名词",
       "zh": "街区",
       "pos": "n.m.",
       "fr": "quartier"
      },
      {
       "g": "阳性名词",
       "zh": "高速火车（=Train à grande vitesse）",
       "pos": "n.m.",
       "fr": "TGV"
      },
      {
       "g": "阳性名词",
       "zh": "旅游业",
       "pos": "n.m.",
       "fr": "tourisme"
      },
      {
       "g": "阳性名词",
       "zh": "火车",
       "pos": "n.m.",
       "fr": "train"
      },
      {
       "g": "阴性名词",
       "zh": "考古学",
       "pos": "n.f.",
       "fr": "archéologie"
      },
      {
       "g": "阴性名词",
       "zh": "吻",
       "pos": "n.f.",
       "fr": "bise"
      },
      {
       "g": "阴性名词",
       "zh": "卡片；明信片",
       "pos": "n.f.",
       "fr": "carte"
      },
      {
       "g": "阴性名词",
       "zh": "目的地",
       "pos": "n.f.",
       "fr": "destination"
      },
      {
       "g": "阴性名词",
       "zh": "明信片",
       "pos": "n.f.",
       "fr": "carte postale"
      },
      {
       "g": "阴性名词",
       "zh": "监狱",
       "pos": "n.f.",
       "fr": "prison"
      },
      {
       "g": "阴性名词",
       "zh": "法国国营铁路公司（=Société nationale des chemins de fer français）",
       "pos": "n.f.",
       "fr": "SNCF"
      },
      {
       "g": "阴性名词",
       "zh": "速度",
       "pos": "n.f.",
       "fr": "vitesse"
      },
      {
       "g": "形容词",
       "zh": "当代的，同时代的",
       "pos": "adj.",
       "fr": "contemporain(e)"
      },
      {
       "g": "形容词",
       "zh": "免费的",
       "pos": "adj.",
       "fr": "gratuit(e)"
      },
      {
       "g": "形容词",
       "zh": "有趣的，有意义的",
       "pos": "adj.",
       "fr": "intéressant(e)"
      },
      {
       "g": "形容词",
       "zh": "地中海的",
       "pos": "adj.",
       "fr": "méditerranéen(enne)"
      },
      {
       "g": "形容词",
       "zh": "邮政的，邮务的",
       "pos": "adj.",
       "fr": "postal(e)"
      },
      {
       "g": "形容词",
       "zh": "年老的；古老的，旧的",
       "pos": "adj.",
       "fr": "vieux (vieille)"
      },
      {
       "g": "介词、连词",
       "zh": "在……四周，在……周围",
       "pos": "loc.prép.",
       "fr": "autour de"
      },
      {
       "g": "地名",
       "zh": "马赛（法国）",
       "pos": "",
       "fr": "Marseille"
      }
     ],
     "cloze": [
      [
       "标题"
      ],
      [
       "La ville de Zidane !"
      ],
      [
       "Pour aller à Marseille"
      ],
      [
       "En ",
       {
        "b": "avion"
       },
       " : Aéroport Marseille Provence"
      ],
      [
       "En voiture : Paris (790 ",
       {
        "b": "kilomètres"
       },
       "), Genève (430 kilomètres), Nice (250 ",
       {
        "b": "kilomètres"
       },
       ")"
      ],
      [
       "En train : Gare Marseille Saint-Charles. 200 ",
       {
        "b": "trains"
       },
       " par ",
       {
        "b": "jour"
       },
       ". À 3 heures de Paris ",
       {
        "b": "par"
       },
       " le TGV Méditerranée"
      ],
      [
       "En bateau : Port de Marseille. 200 ",
       {
        "b": "destinations"
       }
      ],
      [
       "À visiter"
      ],
      [
       "Dans la ville : le Vieux-Port, l'Hôtel de ",
       {
        "b": "ville"
       },
       ", le vieux ",
       {
        "b": "quartier"
       },
       " du Panier, Notre-Dame-de-la-Garde, le palais du Pharo, la Cité ",
       {
        "b": "radieuse"
       },
       " de Le Corbusier"
      ],
      [
       "Musée d'histoire de Marseille. Entrée : ",
       {
        "b": "gratuite"
       }
      ],
      [
       "Musée Cantini (peinture, ",
       {
        "b": "sculpture"
       },
       "). Entrée : 2,50 €"
      ],
      [
       "Musée d'art ",
       {
        "b": "contemporain"
       },
       " (MAC). Entrée : 3 €. Étudiants : 1,50 €"
      ],
      [
       "Musée d'archéologie ",
       {
        "b": "méditerranéenne"
       },
       ". Entrée : 3 €. Étudiants : gratuit"
      ],
      [
       "Autour de Marseille"
      ],
      [
       "Visites en ",
       {
        "b": "bateau"
       },
       " : le château d'If et ",
       {
        "b": "les"
       },
       " îles du Frioul : la ",
       {
        "b": "prison"
       },
       " du comte de Monte-Cristo"
      ],
      [
       "Les ",
       {
        "b": "calanques"
       },
       " : par la ",
       {
        "b": "mer"
       },
       ", entre Marseille et Cassis"
      ]
     ],
     "text": [
      {
       "h": "标题"
      },
      {
       "zh": "Zidane 的城市！",
       "fr": "La ville de Zidane !"
      },
      {
       "h": "Pour aller à Marseille"
      },
      {
       "zh": "乘飞机：Marseille Provence 机场",
       "fr": "En avion : Aéroport Marseille Provence"
      },
      {
       "zh": "驾车：Paris（790 公里），Genève（430 公里），Nice（250 公里）",
       "fr": "En voiture : Paris (790 kilomètres), Genève (430 kilomètres), Nice (250 kilomètres)"
      },
      {
       "zh": "乘火车：Marseille Saint-Charles 火车站。每天 200 趟列车。乘 TGV Méditerranée，离 Paris 3 小时",
       "fr": "En train : Gare Marseille Saint-Charles. 200 trains par jour. À 3 heures de Paris par le TGV Méditerranée"
      },
      {
       "zh": "乘船：Marseille 港。200 个目的地",
       "fr": "En bateau : Port de Marseille. 200 destinations"
      },
      {
       "h": "À visiter"
      },
      {
       "zh": "在市内：Vieux-Port，Hôtel de ville，Panier 的老街区，Notre-Dame-de-la-Garde，Pharo 宫殿，Le Corbusier 设计的 Cité radieuse",
       "fr": "Dans la ville : le Vieux-Port, l'Hôtel de ville, le vieux quartier du Panier, Notre-Dame-de-la-Garde, le palais du Pharo, la Cité radieuse de Le Corbusier"
      },
      {
       "zh": "Marseille 历史博物馆。门票：免费",
       "fr": "Musée d'histoire de Marseille. Entrée : gratuite"
      },
      {
       "zh": "Cantini 博物馆（绘画、雕塑）。门票：2,50 欧元",
       "fr": "Musée Cantini (peinture, sculpture). Entrée : 2,50 €"
      },
      {
       "zh": "当代艺术博物馆（MAC）。门票：3 欧元。学生：1,50 欧元",
       "fr": "Musée d'art contemporain (MAC). Entrée : 3 €. Étudiants : 1,50 €"
      },
      {
       "zh": "地中海考古博物馆。门票：3 欧元。学生：免费",
       "fr": "Musée d'archéologie méditerranéenne. Entrée : 3 €. Étudiants : gratuit"
      },
      {
       "h": "Autour de Marseille"
      },
      {
       "zh": "乘船参观：château d'If 和 Frioul 群岛：Monte-Cristo 伯爵的监狱",
       "fr": "Visites en bateau : le château d'If et les îles du Frioul : la prison du comte de Monte-Cristo"
      },
      {
       "zh": "Calanques：走海路，在 Marseille 和 Cassis 之间",
       "fr": "Les calanques : par la mer, entre Marseille et Cassis"
      }
     ]
    }
   ]
  }
 ]
}];
