// English glosses. EN_V: word → meaning ("n:word" overrides for one leçon). EN_T: one entry per text row (headers included).
window.EN_V = {
  // 1
  'bonjour': 'hello, good morning', 'mari': 'husband', 'monsieur': 'sir, Mr', 'nom': 'surname, name', 'prénom': 'first name',
  'bienvenue': 'welcome', 'femme': 'woman; wife', 'madame (pl. mesdames)': 'madam, Mrs', 'nationalité': 'nationality',
  'étudiant(e)': '(university) student', 'Français(e)': 'French person', 'Italien(ne)': 'Italian person',
  "appeler (s')": 'to be called (one\'s name is)', 'être': 'to be', 'français(e)': 'French', 'italien(ne)': 'Italian',
  'ma': 'my (before a feminine singular noun)', 'mon': 'my (before a masculine singular noun)', 'ce': 'this, it',
  'elle': 'she, it (subject)', 'il': 'he, it (subject)', 'je': 'I (subject)', 'qui': 'who', 'tu': 'you (informal, subject)',
  'vous': 'you (formal / plural, subject)', 'non': 'no', 'oui': 'yes', 'et': 'and', 'voici': 'here is, this is',
  // 2
  'café': 'coffee; café', 'cours': 'class, course', 'français': 'French (language)', 'Japon': 'Japan',
  'professeur': 'teacher, professor', 'rendez-vous': 'appointment, date', 'téléphone': 'telephone', 'thé': 'tea',
  'France': 'France', 'Suisse': 'Switzerland', 'assistant(e)': 'assistant', 'Belge': 'Belgian person',
  'Chinois(e)': 'Chinese person', 'directeur(trice)': 'director, manager', 'Espagnol(e)': 'Spanish person',
  'Japonais(e)': 'Japanese person', 'secrétaire': 'secretary', 'habiter': 'to live (in)', 'belge': 'Belgian',
  'chinois(e)': 'Chinese', 'espagnol(e)': 'Spanish', 'japonais(e)': 'Japanese', 'sympa': 'nice, friendly (informal)',
  'à': 'at, in, to', 'dans': 'in, inside', 'en': 'in (+ feminine country)', 'ou': 'or', 'ah': 'ah! oh!',
  'sur rendez-vous': 'by appointment', "s'il vous plaît": 'please', 'Genève': 'Geneva',
  // 3
  'âge': 'age', 'bébé': 'baby', 'Canada': 'Canada', 'e-mail': 'email', 'fils': 'son', 'garçon': 'boy',
  'adresse': 'address', 'fille': 'girl; daughter', 'journée': 'day (all day long)', 'Notre-Dame': 'Our Lady (Notre-Dame)',
  'rue': 'street', 'ami(e)': 'friend', 'aller': 'to go; to be (health)', 'avoir': 'to have',
  'parler': 'to speak, to talk', 'quel(le)': 'which, what', 'son': 'his, her, its (before a masc. singular noun)',
  'ton': 'your (informal, before a masc. singular noun)', 'votre': 'your (formal / plural, before a singular noun)',
  'ça': 'this, that (informal)', 'toi': 'you (stressed, informal)', '3:vous': 'you (stressed, formal / plural)',
  'alors': 'so, then', 'bien': 'well', 'comment': 'how', 'maintenant': 'now', 'avec': 'with',
  'merci': 'thank you', 'salut': 'hi; bye (informal)', 'un(e)': 'a, an, one', 'Montréal': 'Montreal', 'Paris': 'Paris',
  // 4
  'an': 'year; years old', 'cinéma': 'cinema, film', 'espagnol': 'Spanish (language)', 'golf': 'golf', 'monde': 'world',
  'Sénégal': 'Senegal', 'sport': 'sport', 'volley-ball': 'volleyball', 'Belgique': 'Belgium',
  'correspondance': 'correspondence, letters', 'danse': 'dance', 'Europe': 'Europe', 'lecture': 'reading',
  'musique': 'music', 'nature': 'nature', 'photo': 'photography; photo', 'sœur': 'sister', 'boulanger(ère)': 'baker',
  'correspondant(e)': 'pen pal, correspondent', 'aimer': 'to love, to like', 'chercher': 'to look for',
  'classique': 'classical', 'guyanais(e)': 'Guianese', 'québécois(e)': 'Quebecer, from Quebec', 'moi': 'me (stressed)',
  'aussi': 'also, too', 'beaucoup': 'a lot, very much', 'souvent': 'often', 'un peu': 'a little', 'de': 'from',
  'Bruxelles': 'Brussels', 'Cayenne': 'Cayenne (capital of French Guiana)', 'Dakar': 'Dakar (Senegal)', 'Lausanne': 'Lausanne (Switzerland)',
  // 5
  'blouson': 'jacket', 'chapeau': 'hat', 'côté': 'side', 'fauteuil': 'armchair', 'lit': 'bed', 'livre': 'book',
  'mur': 'wall', 'objet': 'object, thing', 'ordinateur': 'computer', 'sac': 'bag', 'verre': 'glass',
  'affiche': 'poster', 'assiette': 'plate', 'chaise': 'chair', 'chambre': 'bedroom, room', 'droite': 'right (side)',
  'étagère': 'shelf', 'fenêtre': 'window', 'gauche': 'left (side)', 'table': 'table', 'chat(te)': 'cat',
  'trouver': 'to find', 'que': 'what', 'au-dessous': 'underneath, below', 'au-dessus': 'above, on top',
  '5:avec': 'with (having)', 'contre': 'against', 'à côté (de)': 'next to', '5:de': 'of (possession)',
  'devant': 'in front of', 'à droite (de)': 'to the right (of)', 'à gauche (de)': 'to the left (of)',
  'sous': 'under', 'sur': 'on', 'voilà': 'there it is, that\'s it', 'il y a': 'there is, there are',
  'là': 'there; well (in "oh là là")', 'oh': 'oh!',
  // 6
  'homme': 'man', 'jean': 'jeans', 'pantalon': 'trousers', 'portrait-robot': 'identikit picture',
  'tee-shirt': 'T-shirt', 'vêtement': 'piece of clothing', 'basket': 'sneaker, trainer', 'chaussure': 'shoe',
  'chemise': 'shirt', 'chose': 'thing', 'couleur': 'colour', 'lunettes': 'glasses', 'porter': 'to wear',
  'autre': 'other', 'blanc(che)': 'white', 'bleu(e)': 'blue', 'blond(e)': 'blond, fair-haired',
  'brun(e)': 'brown; dark-haired', 'grand(e)': 'tall, big', 'leur, leurs': 'their', 'noir(e)': 'black',
  'petit(e)': 'short, small', 'rouge': 'red', 'vert(e)': 'green', 'lui': 'him (stressed)', "d'accord": 'OK, agreed',
  'ne… pas': 'not',
  // 7
  'euro': 'euro', 'pull': 'jumper, sweater', 'shopping': 'shopping', 'type': 'type, kind', 'robe': 'dress',
  'taille': 'size', 'coûter': 'to cost', 'faire': 'to make, to do; to come to (a price)', '7:trouver': 'to find, to think of',
  'bon(ne)': 'well, right (interjection)', 'cher(ère)': 'expensive', 'gris(e)': 'grey', 'joli(e)': 'pretty',
  '7:bien': 'really, quite', 'combien': 'how much, how many', 'très': 'very', '7:et': 'plus (in adding)',
  'pour': 'for', '*hum': 'hmm',
  // 8
  'coin': 'corner', 'écrivain': 'writer', 'film': 'film, movie', 'poème': 'poem', 'poète': 'poet',
  'tableau¹': 'painting', 'tableau²': 'table, chart', 'tapis': 'rug, carpet', 'orange': 'orange', 'artiste': 'artist',
  'môme': 'kid (informal)', 'musicien(ne)': 'musician', 'peintre': 'painter', 'sculpteur(trice)': 'sculptor',
  'entre': 'between', 'des': 'of the (de + les)', 'du': 'of the (de + le)',
  // 9
  'appartement': 'flat, apartment', 'bout': 'end', 'bureau': 'desk; office', 'couloir': 'corridor', 'étage': 'floor, storey',
  'immeuble': 'building', 'mètre': 'metre', 'mètre carré': 'square metre', 'mois': 'month', 'parking': 'car park',
  'placard': 'cupboard, closet', 'plan': 'floor plan', 'rez-de-chaussée': 'ground floor', 'agence': 'agency',
  'agence immobilière': 'estate agency', 'annonce': 'notice, advertisement', 'petite annonce': 'classified ad',
  'avenue': 'avenue', 'cuisine': 'kitchen; cooking', 'douche': 'shower', 'entrée': 'entrance; hall',
  'face': 'face, side', 'salle': 'room', 'salle de bains': 'bathroom', 'toilettes': 'toilet', 'responsable': 'person in charge',
  'louer': 'to rent', 'ancien(ne)': 'old, former', 'bruyant(e)': 'noisy', 'clair(e)': 'bright, light; clear',
  'immobilier(ère)': 'real-estate (adj.)', 'premier(ère)': 'first', 'récent(e)': 'recent, new', 'sombre': 'dark',
  'troisième': 'third', 'où': 'where', 'chez': 'at (someone\'s place)',
  // 10
  'bus': 'bus', 'jardin': 'garden, park', 'métro': 'underground, metro', 'musée': 'museum', 'opéra': 'opera; opera house',
  'pardon': 'sorry, excuse me', 'pied': 'foot', 'pont': 'bridge', 'rollers': 'roller skates', 'travail': 'work',
  'vélo': 'bike', 'banque': 'bank', 'ligne': 'line', 'moto': 'motorbike', 'place': 'square', 'poste': 'post office',
  'voiture': 'car', 'continuer': 'to continue', 'entrer': 'to enter', 'passer': 'to pass, to go by',
  'prendre': 'to take', 'traverser': 'to cross', 'direct(e)': 'direct', 'après': 'after, then', 'droit': 'straight',
  'ensuite': 'next, then', '10:là': 'there', 'loin': 'far', 'tout': 'quite, all (in "tout droit")',
  'jusque': 'as far as, until', 'par': 'through, by, via', 'bien sûr': 'of course',
  // 11
  'air': 'air', 'air conditionné': 'air conditioning', 'bar': 'bar', 'bord': 'edge; shore', 'circuit': 'tour, circuit',
  'conseil': 'advice', 'est': 'east', 'hélicoptère': 'helicopter', 'jour': 'day', 'nord': 'north', 'ouest': 'west',
  'restaurant': 'restaurant', 'sud': 'south', 'voyage': 'journey, trip', 'week-end': 'weekend', 'carte': 'map',
  'île': 'island', 'mer': 'sea', 'piscine': 'swimming pool', 'plage': 'beach', 'réception': 'reception',
  'télévision': 'television', 'terrasse': 'terrace', 'ville': 'town, city', 'agence de voyages': 'travel agency',
  'partir': 'to leave, to set off', 'visiter': 'to visit', '11:bon(ne)': 'good', 'conditionné(e)': 'conditioned',
  'parfait(e)': 'perfect', 'on': 'we, people, one', '11:bien sûr': 'of course', 'juste': 'just, exactly', 'puis': 'then',
  // 12
  'aéroport': 'airport', 'aquarium': 'aquarium', 'art': 'art', 'avion': 'plane', 'bateau': 'boat', 'billet': 'ticket',
  'centre': 'centre', 'château': 'castle', 'hôtel': 'hotel; large public building', 'hôtel de ville': 'town hall',
  'kilomètre': 'kilometre', 'office': 'office, bureau', 'palais': 'palace', 'port': 'port, harbour',
  'quai': 'platform; quay', 'quartier': 'district, neighbourhood', 'TGV': 'high-speed train', 'tourisme': 'tourism',
  'train': 'train', 'archéologie': 'archaeology', 'bise': 'kiss (on the cheek)', '12:carte': 'card; postcard',
  'destination': 'destination', 'carte postale': 'postcard', 'prison': 'prison', 'SNCF': 'French national railways',
  'vitesse': 'speed', 'contemporain(e)': 'contemporary', 'gratuit(e)': 'free (of charge)', 'intéressant(e)': 'interesting',
  'méditerranéen(enne)': 'Mediterranean', 'postal(e)': 'postal', 'vieux (vieille)': 'old', 'autour de': 'around',
  'Marseille': 'Marseille',
  // 13
  '13:aller': 'outward journey; single (ticket)', 'aller-retour': 'return ticket', 'départ': 'departure', 'dimanche': 'Sunday',
  'horaire': 'timetable', 'jeudi': 'Thursday', 'lundi': 'Monday', 'mardi': 'Tuesday', 'matin': 'morning', 'mercredi': 'Wednesday',
  'renseignement': 'information', 'samedi': 'Saturday', 'tarif': 'fare, price', 'vendredi': 'Friday', 'classe': 'class',
  'gare': 'railway station', 'heure': 'hour; time, o\'clock', 'pendule': 'clock', '13:place': 'seat; room, space', 'voie': 'track, platform; way',
  'après-midi': 'afternoon', 'employé(e)': 'employee', 'complet(ète)': 'full; complete', 'désolé(e)': 'sorry',
  'deuxième': 'second', 'prochain(e)': 'next', 'simple': 'single; simple', 'quand': 'when',
  // 14
  'agenda': 'diary, planner', 'cabinet': 'practice, office', 'docteur': 'doctor', 'institut': 'institute', 'journal': 'newspaper',
  'reste': 'rest, remainder', 'soir': 'evening', 'coiffure': 'hairstyle; hairdressing', 'guitare': 'guitar', 'réunion': 'meeting',
  'semaine': 'week', 'société': 'company; society', 'surprise': 'surprise', 'vacances': 'holidays', 'vie': 'life',
  'acteur(trice)': 'actor, actress', 'informaticien(ienne)': 'computer scientist, IT specialist', 'commencer': 'to begin, to start',
  '14:faire': 'to do (for a living)', 'rentrer': 'to come back, to go home', 'travailler': 'to work', 'voir': 'to see',
  'possible': 'possible', '14:quel(le)': 'what (a)! (exclamation)', 'tous, toutes': 'all, every', '14:là': 'here, there',
  'seulement': 'only', 'tard': 'late', 'tôt': 'early', 'donc': 'so, well then', 'mais': 'but; (surprise) why…!',
  'vers': 'around, towards (time)', 'ben': 'well, er (hesitation)', 'Londres': 'London', 'Vendôme': 'Vendôme (France)',
  // 15
  'athlétisme': 'athletics', 'déjeuner': 'lunch; to have lunch', 'enfant': 'child', 'foot': 'football (informal)', 'footing': 'jogging',
  'marché': 'market', 'ménage': 'housework', 'petit(-)déjeuner': 'breakfast', 'ski': 'skiing', 'témoignage': 'testimony, account',
  'tennis': 'tennis', 'boîte': 'box; nightclub', 'campagne': 'countryside', 'course': 'run, race; (pl.) shopping',
  'gymnastique': 'gymnastics', 'natation': 'swimming', 'dormir': 'to sleep', 'écouter': 'to listen (to)', 'écrire': 'to write',
  "habiller(s')": 'to get dressed', 'jouer': 'to play', 'laver(se)': 'to wash (oneself)', 'lever(se)': 'to get up',
  'lire': 'to read', '15:prendre': 'to have (food, drink)', 'préparer': 'to prepare, to get (someone) ready', 'reposer(se)': 'to rest',
  'général(e), pl.m. généraux': 'general', "d'abord": 'first', 'en général': 'in general, usually',
  'faire des / les courses': 'to do the shopping', 'faire le ménage': 'to do the housework',
  // 16
  'entraînement': 'training', 'fruit': 'fruit', 'janvier': 'January', 'jus': 'juice', 'match': 'match', 'stress': 'stress',
  'yaourt': 'yoghurt', 'céréales': 'cereal', 'famille': 'family', 'musculation': 'weight training', 'toilette': 'washing, getting ready',
  'champion(ne)': 'champion', 'coucher(se)': 'to go to bed', 'détendre(se)': 'to relax', "endormir(s')": 'to fall asleep',
  "entraîner(s')": 'to train', 'éviter': 'to avoid', 'manger': 'to eat', 'nager': 'to swim', 'promener(se)': 'to go for a walk',
  'recommencer': 'to start again', 'regarder': 'to watch, to look at', 'reprendre': 'to resume, to take up again',
  'retourner': 'to go back, to return', 'sortir': 'to go out', 'terminer(se)': 'to end', 'actuel(le)': 'current, present',
  'difficile': 'difficult', 'habituel(le)': 'usual', 'libre': 'free', 'long(ue)': 'long', 'nouveau(nouvelle)': 'new',
  'peu': 'little, not much', 'bravo': 'well done!',
};

window.EN_T = {
  1: ['Dialogue 1', '– Hello, sir. Your name is…?', '– Doucet. Yves Doucet. And this is my wife, Alice.', '– Hello, madam.',
    'Dialogue 2', '– Hello. I\'m Alice Doucet. Are you Mrs Falco?', '– Hello. Yes, my name is Nicole Falco. Aldo, my husband.',
    '– Arnaud?', '– No. Aldo. His name is Aldo.',
    'Dialogue 3', '– Who is it?', '– It\'s Aldo. Aldo Falco.', '– Aldo? Is he Italian?', '– Yes, and her, that\'s Nicole, she\'s French.',
    'Dialogue 4', '– Your name is Giacomo! Are you Italian?', '– Yes, yes. I\'m Italian.'],
  2: ['– Who is it?', '– It\'s Naoko, isn\'t it?', '– Naoko?', '– Yes, Naoko Yamada. She\'s a student.', '– Is she nice?',
    '– Yes. She\'s in the French class, she\'s Japanese.', '– Does she live in France or in Japan?', '– She lives in Switzerland, in Geneva.'],
  3: ['Dialogue 1', '– Hi, Céline, are you well?', '– Yes, I\'m fine. And you?', '– I\'m fine, thanks… I live in Montreal now, with my wife.',
    '– In Canada?', '– Yes, yes, in Canada.', '– Ah! That\'s great. And what\'s your address?',
    '– My address? So, it\'s: David Delage… 35 Notre-Dame Street, Montreal.', '– And do you have an email address?',
    '– Yes, it\'s: ddelage@hotmail.com.',
    'Dialogue 2', '– How is your Spanish friend?', '– Luis? He\'s fine. He\'s in Paris with his son. He speaks French now.', '– Do you have his address?'],
  4: ['Diouf', 'Hi! My name is Diouf. I\'m 29. I live in Dakar, in Senegal. I often go to the cinema. I\'m looking for a pen pal in France or in Canada.',
    'My email: diouf29@webzine.com',
    'Antoine', 'My name is Antoine. I\'m 25 and I live in Brussels, in Belgium. I\'m a student. I like reading, nature and classical music.',
    'My email: antoine.leconte@webzine.com',
    'Marion', 'Me, I\'m Marion. I\'m from Quebec. I\'m 18 and I live in Montreal. I like sport: volleyball, golf… I\'m looking for a friend in Europe.',
    'My email: marion@webzine.net',
    'Pauline', 'Hello, my name is Pauline and I\'m 31. I\'m Guianese: I live in Cayenne. I\'m a secretary. I\'m looking for a pen pal aged 30 to 40. I speak French, English and Spanish. I really love dancing.',
    'My email: pauline31@webzine.fr',
    'Sandro', 'My name is Sandro and I live in Switzerland, in Lausanne. I\'m 22. I\'m a baker. I like photography.',
    'My email: sandro.carre@webzine.ch'],
  5: ['– Her hat and her jacket, is that it?', '– Yes, her hat and her jacket. They\'re in Mélanie\'s room, under the shelf next to the window.',
    '– The shelf with books, to the left of the window?', '– No! The shelf against the wall, to the right of the window… under the posters! Oh dear!',
    '– To the right of… Ah yes! On the chair, there\'s a jacket and a hat.', '– There you go! That\'s it!'],
  6: ['– So… Are they tall? Short?', '– There\'s one man, tall and… blond. Yes, that\'s right, he\'s blond. The other man, he\'s short and dark-haired.',
    '– OK. Do they wear glasses?', '– No, no, they don\'t wear glasses.', '– And their clothes?',
    '– The blond man is wearing a white T-shirt and black trousers… No, blue, blue trousers. They\'re jeans. The dark-haired man, he has a jacket.',
    '– What colour?', '– The colour of his jacket… black… no, it isn\'t black… red… yes, red.', '– Anything else?',
    '– Yes, his shirt is green.', '– And his shoes?', '– Ah! They\'re sneakers.'],
  7: ['Dialogue 1', '– Hello, ladies, what are you looking for?', '– Clothes for my daughter and my son.', '– How old are they?',
    '– My daughter is 16 and my son 14.', '– For girls, it\'s on the shelves on the left, and for boys, on the right.',
    'Dialogue 2', '– What do you think of these trousers?', '– I quite like this kind of trousers, they\'re very pretty!',
    '– What colours do you have, please?', '– These trousers? There\'s blue, grey or black.', '– How much are they?', '– 59 euros.',
    '– That\'s not very expensive!', '– Hmm, hmm. Not very expensive…', '– Do you have the grey in size 38?', '– Yes, yes.',
    '– This green dress, do you like it?',
    'Dialogue 3', '– Oh, no! Not at all.', '– Oh really! And this jumper? It\'s pretty, isn\'t it?', '– Yes, the blue and white one, I quite like it.',
    '– How much does it cost?', '– 35 euros.', '– Right, so… This jumper and these trousers, how much does that come to, please?',
    '– 35 plus 59… that comes to 94 euros, madam.', '– Here you are.'],
  8: ['The film La Môme', 'La Môme, a film by Olivier Dahan. Starring Marion Cotillard, Gérard Depardieu…', 'Describe the picture',
    'The poet is between Henri Matisse and Camille Claudel.', 'Claude Debussy is on the right in the painting.', 'The sculptor is a woman.',
    'Colette is to the left of the painter.', 'The poet is to the left of the sculptor and to the right of the painter.',
    'Next to Claude Debussy, there is the sculptor.', 'The painter is next to the writer.', 'The writer is on the left in the painting.',
    'Guillaume Apollinaire is not the musician.'],
  9: ['Email', 'Dear Sir,', 'The building is on the corner of rue Victor-Hugo and rue Michelet. It\'s a new building with a car park. The flat is on the third floor, with a lift.',
    'The kitchen is to the left of the entrance.',
    'Opposite the kitchen, you have the toilet and a bathroom with a shower. The bedroom is at the end of the corridor, on the right: there\'s a bed and a desk with a chair.',
    'To the left of the corridor, there\'s the living room. It\'s quiet.', 'You have two cupboards in the flat.', 'Best regards.',
    'Alain Dauger', 'Manager of the Loca-loisirs agency'],
  10: ['– Excuse me, sir. The Louvre museum, which way is it?', '– Oh dear! You\'re far away. Take the metro.', '– I don\'t like the metro.',
    '– Then go by bus or by bike: there are Vélib\' bikes on the street corner.', '– No, no. I\'ll go on foot.',
    '– Fine. Then go this way. Cross boulevard Haussmann and take rue Scribe in front of you. Turn left into rue Auber. Go past the post office and the bank and you arrive at place de l\'Opéra. OK?',
    '– Yes, yes.', '– Next, take the big avenue opposite and keep going straight on, right to the end.', '– Hmm, hmm.',
    '– And after that, cross rue de Rivoli and go into the Louvre courtyard. On the right, you have the Tuileries garden and on the left the Louvre. The museum entrance is under the Pyramid.',
    '– Thanks, er… the Vélib\' bikes, where are they?'],
  11: ['– Right, so, on the first day, you leave from Paris and you arrive at Fort-de-France airport. There, you take a bus to your hotel, La Marina, on the west of the island.',
    '– Are we by the sea?', '– Yes, it\'s a hotel next to the beach. Your room has a terrace facing the sea.',
    '– And is there a bathroom in the room?',
    '– Yes, of course, sir: a bathroom, the telephone, the television and air conditioning. And, in the hotel, you have two bars, two restaurants, some shops and a swimming pool.',
    '– Ah! That\'s perfect! And do we visit the island too?',
    '– Yes, by helicopter. You also go by bus to Fort-de-France and to Sainte-Luce in the south, to Mount Pelée and to Saint-Pierre, in the north… Ah! of course, visit the Gauguin museum, next to your hotel. It\'s really nice!'],
  12: ['Headline', 'Zidane\'s city!', 'Getting to Marseille', 'By plane: Marseille Provence Airport',
    'By car: Paris (790 kilometres), Geneva (430 kilometres), Nice (250 kilometres)',
    'By train: Marseille Saint-Charles station. 200 trains a day. 3 hours from Paris by the TGV Méditerranée',
    'By boat: Port of Marseille. 200 destinations', 'Things to visit',
    'In the city: the Old Port, the Town Hall, the old Panier district, Notre-Dame-de-la-Garde, the Pharo palace, Le Corbusier\'s Cité radieuse',
    'Museum of the History of Marseille. Admission: free', 'Cantini Museum (painting, sculpture). Admission: €2.50',
    'Museum of Contemporary Art (MAC). Admission: €3. Students: €1.50', 'Museum of Mediterranean Archaeology. Admission: €3. Students: free',
    'Around Marseille', 'Boat trips: the Château d\'If and the Frioul islands: the prison of the Count of Monte Cristo',
    'The calanques: by sea, between Marseille and Cassis'],
  13: ['– Hello, sir, I\'d like a single from Paris to Marseille, please.', '– When are you leaving?', '– Next Tuesday.', '– The 15th?',
    '– Yes, that\'s right…', '– Morning or afternoon?', '– Morning.', '– Well… There\'s a train at 7:18… another at 8:46… at 9:22…',
    '– The 7:18 train, please.', '– Ah! I\'m sorry, sir. That train is full.', '– And the 8:46 train, is it full too?',
    '– No, there are seats.', '– That\'s perfect.', '– A single or a return?', '– A single. Second class.', '– Here you are.', '– How much is it?'],
  14: ['– Why, it\'s Isabelle!… Isabelle, Isabelle!', '– Farid! Oh! What a surprise! How are you?', '– Fine. And you? But what are you doing here?',
    '– Well, you see, I work here. I\'m a secretary at the Institut français… And you, what do you do for a living now?',
    '– I\'m an IT specialist.', '– Ah! Yes, and where do you work? In London?',
    '– No, no. I work in Paris, but I live in Vendôme. I take the TGV to go to work.', '– Oh? Every day?',
    '– No, I go to Paris only from Monday to Wednesday. The rest of the week, I work from home.', '– And what time do you leave in the morning?',
    '– Very early. At 6:30. And I get home late in the evening, around 9 or 9:30. But it\'s only three days a week, it\'s fine.',
    '– So what are you doing in London?', '– Ah! Here, I\'m on holiday.'],
  15: ['Question', 'Generally, what do you do on Sunday mornings?', 'Account 1',
    'Sunday morning? First I go jogging. Then I play football or tennis with friends. And in the afternoon, I rest.', 'Account 2',
    'Me, I do the shopping. And my wife gets the children ready and plays with them. Or else we go out for the day. And we often go to the countryside.', 'Account 3',
    'On Sunday morning, I do the housework; afterwards, I have a wash and get dressed. Then I listen to music, read, or write to friends.', 'Account 4',
    'Me, every Saturday night I go clubbing and I get home around 5 or 6 in the morning. So on Sundays, I sleep! And I get up at noon.', 'Account 5',
    'Ah! My wife and I have breakfast around 9. Then we go to the market. At noon, we have lunch with our children, at their place or ours.'],
  16: ['Article', 'Well done, Laure! At 22, she is French, European and world swimming champion. But a champion\'s life is hard!',
    'She gets up every morning around 6. She has a wash. Then she gets dressed and has breakfast: fruit, yoghurt, cereal and orange juice. At 7, she is at the pool. She trains until 10. Then she goes back to her flat next to the pool. She starts training again in the afternoon, at 3:30. She swims 15 kilometres a day! Her day ends around 7:30.',
    'She goes home. She eats, watches a little TV and phones friends. She goes to bed early, around 10. She sleeps eight hours a night.',
    'On Saturday evening, she is free. She goes out, to a restaurant or the cinema with friends. On Sunday, she sleeps until noon. She spends the afternoon with friends or with her family.',
    'And on Monday, a new week begins again…', 'Relaxing', 'She listens to music.', 'She plays cards.', 'She sleeps a lot.'],
};
