// 记忆提示：{词根} 会加粗显示。按课本单词原样作键。
window.TIPS = {
  // Leçon 1
  'bonjour': '{bon} 好 + {jour} 日子 = 好日子 → 你好',
  'mari': '和 {mari}age（婚姻）、se {mari}er（结婚）同根；英语 marry',
  'monsieur': '{mon} 我的 + {sieur}（老爷，同 seigneur）→ 我的老爷 → 先生；读作 [məsjø]，on 读 [ə]',
  'nom': '和英语 {name}、拉丁 {nomen} 同源；prénom = pré（在前）+ nom',
  'prénom': '{pré} 在……之前 + {nom} 姓 → 放在姓前面的名字',
  'bienvenue': '{bien} 好好地 + {venue} 来（venir 的过去分词）→ 欢迎光临；英语 welcome 构词相同',
  'femme': '读作 [fam]，emme 读 [am]；女性的 {fém}inin 同根',
  'madame (pl. mesdames)': '{ma} 我的 + {dame} 夫人；复数两部分都变：mes + dames',
  'nationalité': '{nation} 民族 + {-al} + {-ité}（名词后缀，阴性）；-ité ≈ 英语 -ity',
  'étudiant(e)': '{étudi}er 学习 + {-ant} 做……的人 → 学生；英语 student',
  'Français(e)': '{France} → {Franç}ais；c 加软音符 ç 读 [s]；表示「人」时首字母大写',
  'Italien(ne)': '{Itali}e + {-en}；阴性双写 n：italienne；表示「人」时大写',
  'français(e)': '形容词小写；{-ais} 是常见国籍后缀（japonais, anglais）',
  'italien(ne)': '形容词小写；-ien → -ienne 双写 n',
  'ma': '阴性单数名词前：ma femme；阳性用 mon',
  'mon': '阳性单数名词前：mon mari；以元音开头的阴性名词也用 mon（mon adresse）',
  'ce': 'c\'est = ce + est，元音前省略成 c\'',
  'elle': '和 il 成对；elles 复数',
  'il': '拉丁 ille（那个）；ils 复数，s 不发音',
  'je': '元音前省略成 j\'：j\'ai, j\'habite',
  'qui': '问「谁」；qu- 开头的都是疑问词家族：qui, que, quel, quand',
  'tu': '对熟人、朋友用；对陌生人用 vous',
  'vous': '既是「您」（礼貌）也是「你们」',
  'non': '英语 no / non-',
  'oui': '读作 [wi]，像英语 we',
  'et': 't 永远不发音，也从不连读',
  'voici': '{voi}s 看（voir）+ {ci} 这里 → 看这里 → 这是',
  // Leçon 2
  'café': '英语 coffee / café；é 读 [e]',
  'cours': '{cour}ir 跑 → 课程是「流过的」一段；英语 course；单复数同形',
  'français': '语言名小写，前面常加 le：le français',
  'Japon': 'Japon → {japon}ais（日本人/日本的）',
  'professeur': '{profess}er 公开宣讲 + {-eur}（做……的人）；英语 professor，口语 prof',
  'rendez-vous': 'rendez-vous 原意「你们去（某处）」→ 约会；-z 和 s 都不发音',
  'téléphone': '{télé} 远 + {phone} 声音 → 远处的声音；同 télévision（远+看）',
  'thé': '英语 tea；h 不发音',
  'France': 'France → {franç}ais，ç 是为了保持 [s] 音',
  'Suisse': 'Suisse → {suisse}（瑞士人）；双 s 读 [s]',
  'assistant(e)': '{assist}er 协助 + {-ant} 做……的人；英语 assistant',
  'Belge': 'Belgique 比利时 → {belge}；以 -e 结尾，阴阳同形',
  'Chinois(e)': '{Chine} 中国 + {-ois}；阴性 chinoise 的 s 读 [z]',
  'directeur(trice)': '{direct}ion + {-eur}；阴性 -teur → -trice（同 acteur → actrice）；英语 director',
  'Espagnol(e)': '{Espagne} 西班牙 + {-ol}；gn 读 [ɲ]，像「捏」',
  'Japonais(e)': '{Japon} + {-ais}，-ais 是国籍后缀',
  'secrétaire': '{secret} 秘密 + {-aire} → 保管机密的人；英语 secretary',
  'belge': '形容词小写',
  'chinois(e)': '形容词小写；le chinois = 中文',
  'espagnol(e)': '形容词小写；l\'espagnol = 西班牙语',
  'japonais(e)': '形容词小写；le japonais = 日语',
  'sympa': '{sympa}thique 的口语缩写；英语 sympathetic；只有一种形式',
  'à': '带重音的 à 是介词，a 是 avoir 的变位（il a），别混',
  'dans': '在……里面：dans le cours, dans la chambre',
  'en': '阴性国家前用 en：en France, en Suisse；阳性国家用 au：au Japon',
  'ou': '「或者」不带重音；où（哪里）带重音',
  'ah': '感叹词，h 不发音',
  'sur rendez-vous': '{sur} 根据 + rendez-vous → 凭预约',
  's\'il vous plaît': '{si} 如果 + {il} + vous {plaît}（使您高兴）→ 如果您愿意 → 请；缩写 SVP',
  'Genève': '读作 [ʒənɛv]；英语 Geneva',
  // Leçon 3
  'âge': 'â 的长音符常表示古法语里掉了一个字母（古法语 aage）；英语 age',
  'bébé': '英语 baby；两个 é',
  'Canada': '阳性国家：au Canada',
  'e-mail': '借自英语，也说 courriel（courrier 信件 + électronique）',
  'fils': '读作 [fis]，l 不发音、s 发音；英语 filial（子女的）同根',
  'garçon': 'ç 读 [s]；也指餐厅服务员',
  'adresse': '{a} + {dress}er（摆正、指向）→ 指向你的地方；法语只有一个 d，英语 address 两个 d',
  'fille': '{fil}s 儿子 → {fille} 女儿；ill 读 [ij]',
  'journée': '{jour} 一天 + {-née}（表示一段持续时间）→ 一整天；同 soir/soirée, an/année',
  'Notre-Dame': '{notre} 我们的 + {dame} 夫人 → 圣母',
  'rue': '英语 route 同源；读 [ʁy]，嘴唇撮圆',
  'ami(e)': '{am}our 爱 / {aim}er 同根；英语 amicable, amiable',
  'quel(le)': 'qu- 疑问家族；四种形式 quel, quelle, quels, quelles 读音都一样',
  'son': '阳性单数前；不管是「他的」还是「她的」，看后面名词的阴阳性',
  'ton': '阳性单数前；阴性用 ta',
  'votre': '单数名词前；复数用 vos',
  'ça': 'cela 的口语缩写；ça va = 一切进展得怎样',
  'toi': '强调式：Et toi ?；对应 moi, lui, elle, nous, vous',
  '3:vous': '强调式与主语同形：Et vous ?',
  'alors': '{à} + {lors}（那时）→ 那时候 → 那么',
  'bien': '{bien} 好地 → {bien}venue；英语 bene-（benefit）同根',
  'comment': '{comme} 如同 + -ment → 以何种方式 → 怎样',
  'maintenant': '{main} 手 + {tenant}（tenir 拿着）→ 手里正拿着 → 此刻',
  'avec': '和……一起：avec ma femme',
  'merci': '原意「恩惠」，英语 mercy 同源；merci beaucoup',
  'salut': '原意「健康、平安」，英语 salute 同源；熟人之间用',
  'un(e)': '不定冠词；un 阳性，une 阴性',
  'Montréal': '{mont} 山 + {réal}（royal 皇家的）→ 皇家山',
  'Paris': 's 不发音：[paʁi]',
  // Leçon 4
  'an': '计算年数：j\'ai 29 ans；同 année（一整年），英语 annual',
  'cinéma': '希腊语 kinêma（运动）→ cinéma{tographe}；英语 cinema',
  'espagnol': '语言名小写，阳性',
  'golf': '借自英语',
  'monde': '英语 mundane（世俗的）同根；tout le monde = 大家',
  'Sénégal': '阳性：au Sénégal → {sénégal}ais',
  'sport': '借自英语',
  'volley-ball': '借自英语 volleyball，法语加连字符',
  'Belgique': '{belg}e + {-ique}；阴性：en Belgique',
  'correspondance': '{co-} 共同 + {respond}re 回应 + {-ance}；英语 correspondence 用 -ence，法语用 -ance',
  'danse': '英语 dance；法语用 s',
  'Europe': '读作 [øʁɔp]',
  'lecture': '{lect}（拉丁 legere 读）+ {-ure} → 阅读；⚠️ 不是英语的「讲座」',
  'musique': '英语 -ic 常对应法语 -ique：music → musique, classic → classique',
  'nature': '英语 nature，拼写相同',
  'photo': '{photo}graphie 的缩写；photo = 光，同 photographe（摄影师）',
  'sœur': 'œ 连写读 [œ]；英语 sister 远亲',
  'boulanger(ère)': '{boule} 圆球 → 圆面包 → {boulang}erie 面包店；阴性 -er → -ère',
  'correspondant(e)': '{correspond}re 通信 + {-ant} 做……的人；同 correspondance',
  'classique': '英语 -ic → 法语 -ique：classic → classique',
  'guyanais(e)': '{Guyane} 圭亚那 + {-ais}',
  'québécois(e)': '{Québec} + {-ois}；写法注意 é 和结尾 c 不变',
  'moi': '强调式：Moi, c\'est Marion.；对应主语 je',
  'aussi': '拉丁 aliud + {sic}（如此）→ 同样',
  'beaucoup': '{beau} 美的 + {coup} 一击 → 漂亮的一下 → 很多',
  'souvent': '拉丁 subinde；ou 读 [u]，ent 读 [ɑ̃]',
  'un peu': '{peu} 少 → un peu 一点；beaucoup 的反义',
  'de': '元音前省略成 d\'；de + le = du，de + les = des',
  'Bruxelles': 'x 读 [s]：[bʁysɛl]',
  'Cayenne': '辣椒 cayenne pepper 就以此地命名',
  'Dakar': '塞内加尔首都',
  'Lausanne': 'au 读 [o]',
  // Leçon 5
  'blouson': '{blouse} 罩衫 + {-on}（小、短）→ 短夹克',
  'chapeau': '拉丁 cappa（帽、斗篷）；英语 cap、chaperon 同源；复数加 x：chapeaux',
  'côté': 'côte（肋骨、侧面）→ côté 旁边；â/ô 常对应古法语的 s：英语 coast',
  'fauteuil': '扶手椅；eu 读 [ø]，-euil 读 [œj]',
  'lit': '英语 litter（担架）同源；t 不发音',
  'livre': '拉丁 liber（书）；英语 library（图书馆）同根，⚠️ library ≠ librairie（书店）',
  'mur': '英语 mural（壁画）同根',
  'objet': '{ob-} 向前 + {jet}er 扔 → 扔到眼前的东西；英语 object',
  'ordinateur': '{ordin}（排序，同 ordre）+ {-ateur} 机器 → 排序处理的机器 → 电脑',
  'sac': '英语 sack；c 发音',
  'verre': '拉丁 vitrum（玻璃）；同 vitre（玻璃窗）；⚠️ 与 vert（绿）、vers（向）同音',
  'affiche': '{a-} + {fich}er（钉住）→ 钉在墙上的东西 → 海报',
  'assiette': '{assi}s 坐下（asseoir）→ 原指「座位、摆放」→ 盘子',
  'chaise': '和 chaire（讲坛）同源；英语 chair',
  'chambre': '英语 chamber 同源；chambre = 卧室',
  'droite': '{droit} 直的、右的 → la droite；英语 adroit（灵巧的，「右手的」）',
  'étagère': '{étage} 层 + {-ère} → 一层层的架子；é 开头常对应英语的 s：étage ≈ stage',
  'fenêtre': 'ê 代替古法语的 s：fenestre；英语 defenestrate（扔出窗外）同根',
  'gauche': '原意「笨拙的」，英语借去 gauche（笨拙）；左手被认为不灵巧',
  'table': '英语 table，拼写相同',
  'chat(te)': '读作 [ʃa]，t 不发音；阴性 chatte',
  'que': '「什么」：qu\'est-ce que；qu- 疑问家族',
  'au-dessous': '{au} + {dessous}（de + sous 下面）→ 在下面',
  'au-dessus': '{au} + {dessus}（de + sur 上面）→ 在上面',
  '5:avec': '表示「带有」：l\'étagère avec des livres',
  'contre': '英语 counter / contra- 同根：靠着、反对',
  'à côté (de)': '{côté} 旁边 → à côté de 在……旁边',
  '5:de': '表示所属：la chambre de Mélanie',
  'devant': '{de} + {avant} 之前 → 在……前面',
  'à droite (de)': '{droite} 右边 → à droite de',
  'à gauche (de)': '{gauche} 左边 → à gauche de',
  'sous': '拉丁 sub；英语 sub-（subway）同根',
  'sur': '拉丁 super；英语 sur-（surface）同根',
  'voilà': '{voi}s 看 + {là} 那里 → 看那里 → 那就是；对应 voici',
  'il y a': '{y} 那里 + {a} 有（avoir）→ 那里有 → 有',
  'là': '带重音的 là 是「那里」，la 是冠词；Oh là là !',
  'oh': '感叹词，h 不发音',
  // Leçon 6
  'homme': '拉丁 homo；英语 human、homicide 同根；h 不发音，可省略：l\'homme',
  'jean': '来自热那亚 Gênes 的布料；读作 [dʒin]',
  'pantalon': '来自意大利喜剧人物 Pantalone，他穿长裤；英语 pants 同源',
  'portrait-robot': '{portrait} 肖像 + {robot} 机器人 → 拼凑出来的画像',
  'tee-shirt': '借自英语 T-shirt',
  'vêtement': '{vêt}ir 穿衣 + {-ement}；ê 代替 s：英语 vest 同根',
  'basket': '借自英语 basketball 篮球鞋；常用复数 des baskets',
  'chaussure': '{chausse}r 穿鞋 + {-ure}；同 chaussette（袜子）',
  'chemise': '英语 chemise（女式衬裙）同源',
  'chose': '拉丁 causa；英语 cause 同源；autre chose = 别的事',
  'couleur': '{coul}（拉丁 color）+ {-eur}；英语 colour 英式拼写多一个 u，正像法语',
  'lunettes': '{lune} 月亮 + {-ette}（小）→ 一对「小月亮」→ 眼镜；总用复数',
  'autre': '拉丁 alter；英语 alter、alternative 同根',
  'blanc(che)': '英语 blank（空白）同源；阴性 blanche 不规则',
  'bleu(e)': '英语 blue；eu 读 [ø]',
  'blond(e)': '英语 blond / blonde 直接借自法语',
  'brun(e)': '英语 brown 同源；brune 读 [bʁyn]',
  'grand(e)': '英语 grand；阳性 d 不发音，阴性 grande 的 d 发音',
  'leur, leurs': '后面的名词是单数用 leur，复数用 leurs',
  'noir(e)': '拉丁 niger；英语 film noir（黑色电影）',
  'petit(e)': '英语 petite（娇小的）直接借自法语阴性形式',
  'rouge': '英语 rouge（胭脂）；同 rougir（脸红）',
  'vert(e)': '英语 verdant（翠绿的）同根；⚠️ 与 verre（玻璃）同音',
  'lui': '强调式：L\'homme brun, lui, il a un blouson.',
  'd\'accord': '{de} + {accord} 一致 → 同意；英语 accord, according',
  'ne… pas': '把动词夹在中间：ils {n\'ont pas} de lunettes',
  // Leçon 7
  'euro': '读作 [øʁo]；复数 euros',
  'pull': '{pull}-over 的缩写，借自英语',
  'shopping': '借自英语；法国人也说 faire les courses',
  'type': '英语 type；口语里 un type 还指「一个家伙」',
  'robe': '英语 robe（长袍）借自法语；法语专指连衣裙',
  'taille': '{taill}er 剪裁 → 剪裁的尺寸；英语 tailor（裁缝）同根',
  'bon(ne)': 'Ah bon ! = 啊，是吗！；阴性双写 n：bonne',
  'cher(ère)': '既是「贵的」也是「亲爱的」（cher ami）；英语 cherish 同根',
  'gris(e)': '英语 grizzled（灰白的）同源',
  'joli(e)': '英语 jolly 同源',
  '7:bien': '表示程度：J\'aime bien = 我挺喜欢',
  'combien': '{com}me + {bien} → 多少',
  'très': '拉丁 trans（穿过）→ 「透」→ 很；très joli 很漂亮',
  '7:et': '表示加法：35 et 59',
  'pour': '为了、对于：pour ma fille',
  '*hum': '星号表示 h 是嘘音 h：前面不省略、不连读',
  // Leçon 8
  'coin': '角落；英语 corner 同源（拉丁 cuneus 楔子）',
  'écrivain': '{écri}re 写 + {-vain} → 作家；é 开头常对应英语的 s：écrire ≈ scribe',
  'film': '借自英语',
  'poème': '{poè}te 诗人 → poème 诗；英语 poem',
  'poète': '{poè}me → poète；英语 poet',
  'tableau¹': '{table} 板 + {-eau}（小）→ 画在木板上的画；复数 tableaux',
  'tableau²': '{table} + {-eau} → 表格；同英语 table（表格）',
  'tapis': '英语 tapestry（挂毯）同根；s 不发音',
  'orange': '英语 orange；作颜色形容词时不变',
  'artiste': '{art} 艺术 + {-iste} 做……的人；英语 artist',
  'môme': '口语，小孩；La Môme = 小麻雀（指歌手 Édith Piaf）',
  'musicien(ne)': '{musique} → {music}ien；阴性 -ienne 双写 n',
  'peintre': '{peind}re 画 → peintre；英语 paint, painter',
  'sculpteur(trice)': '{sculpt}er 雕刻 + {-eur}；p 不发音：[skyltœʁ]；阴性 -trice',
  'entre': '拉丁 inter；英语 inter-（international）同根；entre … et …',
  'des': 'de + les = des：à droite des poètes',
  'du': 'de + le = du：à gauche du peintre',
  // Leçon 9
  'appartement': '{appart}enir 属于 → 属于某人的一套房间；口语 appart；英语 apartment 少一个 p',
  'bout': 'au bout de = 在……尽头',
  'bureau': '原指「盖桌子的粗呢布」→ 书桌 → 办公室；复数 bureaux；英语 bureau',
  'couloir': '{coul}er 流动 + {-oir}（场所）→ 让人流过的地方 → 走廊',
  'étage': 'é 开头对应英语 s：étage ≈ stage（一层）；同 étagère',
  'immeuble': '{im-} 不 + {meuble} 可移动的 → 不能搬的 → 楼房；同 immobilier',
  'mètre': '希腊语 metron（度量）；英语 meter / metre',
  'mètre carré': '{mètre} + {carré} 正方形的 → 平方米，写作 m²',
  'mois': '拉丁 mensis；英语 month 远亲；单复数同形',
  'parking': '借自英语',
  'placard': '{plaqu}er 贴上 → 嵌在墙里的壁橱；⚠️ 英语 placard 是「标语牌」',
  'plan': '平面 → 平面图；英语 plan',
  'rez-de-chaussée': '{rez}（齐平）+ {de} + {chaussée}（路面）→ 与路面齐平的一层',
  'agence': '{ag}ir 行动 + {-ence} → 代理；英语 agency',
  'agence immobilière': '{agence} + {immobilier}（不动产的）',
  'annonce': '{a-} + {nonc}er（宣告）→ 公告；英语 announce',
  'petite annonce': '{petite} 小 + {annonce} → 小广告',
  'avenue': '{a-} + {venu}（来）→ 通向某处的路；英语 avenue',
  'cuisine': '{cuis}（cuire 煮）+ {-ine} → 厨房、烹饪；英语 cuisine',
  'douche': '英语 douche 借自法语',
  'entrée': '{entr}er 进入 + {-ée} → 入口；也指前菜',
  'face': 'en face de = 在……对面；英语 face',
  'salle': '大厅、室；英语 saloon 同源',
  'salle de bains': '{salle} 房间 + {bains} 洗澡 → 浴室；英语 bath 远亲',
  'toilettes': '{toile} 布 + {-ette} → 梳妆用的小布 → 梳洗间；总用复数',
  'responsable': '{répond}re 回应 → responsable 负责的；英语 responsible',
  'ancien(ne)': '英语 ancient 同源；阴性双写 n',
  'bruyant(e)': '{bruit} 噪音 + {-ant} → 吵闹的',
  'clair(e)': '英语 clear / clarity 同根',
  'immobilier(ère)': '{im-} 不 + {mobile} 可移动 + {-ier} → 不动产的；同 immeuble',
  'premier(ère)': '拉丁 primarius；英语 premier、prime 同根',
  'récent(e)': '英语 recent',
  'sombre': '英语 sombre / somber（阴暗的）借自法语',
  'troisième': '{trois} 三 + {-ième}（序数后缀）→ 第三',
  'où': '带重音是「哪里」，不带重音的 ou 是「或者」',
  'chez': '拉丁 casa（房子）→ chez moi = 在我家',
  // Leçon 10
  'bus': 'auto{bus} 的缩写',
  'jardin': '英语 garden 同源；同 jardinier（园丁）',
  'métro': '{métro}politain（大都市的）的缩写',
  'musée': '{muse}（缪斯，艺术女神）+ {-ée} → 缪斯之所；英语 museum',
  'opéra': '英语 opera',
  'pardon': '{par}（彻底）+ {don} 给予 → 宽恕；英语 pardon',
  'pied': '拉丁 pes, pedis；英语 pedal、pedestrian 同根；à pied 步行',
  'pont': '拉丁 pons；英语 pontoon（浮桥）同根',
  'rollers': '借自英语 roller skates',
  'travail': '英语 travail（艰辛劳动）同源；复数 travaux',
  'vélo': '{vélo}cipède 的缩写，velo = 快（同英语 velocity）',
  'banque': '英语 -k 常对应法语 -que：bank → banque',
  'ligne': '英语 line；gn 读 [ɲ]',
  'moto': '{moto}cyclette 的缩写；英语 motor 同根',
  'place': '城市里的广场；英语 place / plaza',
  'poste': '{post}e → postal（邮政的）；英语 post',
  'voiture': '拉丁 vectura（运输）；英语 vehicle 远亲',
  'direct(e)': '英语 direct；同 directeur',
  'après': '{a-} + {près} 近 → 紧接着 → 之后',
  'droit': 'tout droit = 一直往前',
  'ensuite': '{en} + {suite}（后续）→ 接下来；同 suivre（跟随）',
  '10:là': '那里：passez par là',
  'loin': '远；反义 près（近）',
  'tout': 'tout droit 一直往前；作副词表示「完全」',
  'jusque': '常与 à 连用并省略：jusqu\'à, jusqu\'au bout',
  'par': '经过：passez par là；英语 per 同根',
  'bien sûr': '{bien} 很 + {sûr} 确定的 → 当然；英语 sure 同源',
  // Leçon 11
  'air': '英语 air',
  'air conditionné': '{air} 空气 + {conditionné} 调节过的 → 空调；英语 air-conditioned',
  'bar': '借自英语',
  'bord': '英语 border、board 同源；au bord de la mer 在海边',
  'circuit': '{circ}le 圆 → 绕一圈的路线；英语 circuit',
  'conseil': '拉丁 consilium；英语 counsel 同源',
  'est': '东；t 发音：[ɛst]，别和 est（是）混',
  'hélicoptère': '希腊语 {hélico}（螺旋）+ {ptère}（翅膀）→ 螺旋翼',
  'jour': '拉丁 diurnus；同 bonjour、journée；英语 journal（日志）',
  'nord': '英语 north',
  'ouest': '英语 west；读作 [wɛst]',
  'restaurant': '{restaur}er 恢复体力 + {-ant} → 让人恢复元气的地方；英语 restore',
  'sud': '英语 south；d 发音',
  'voyage': '{voie} 路 + {-age} → 走在路上 → 旅行；英语 voyage；Bon voyage !',
  'week-end': '借自英语',
  'carte': '拉丁 charta（纸）；英语 card、chart 同根',
  'île': 'î 的长音符代替古法语的 s：isle；英语 isle、island',
  'mer': '拉丁 mare；英语 marine、mermaid 同根；⚠️ 与 mère（妈妈）同音',
  'piscine': '拉丁 piscis（鱼）→ 养鱼池 → 游泳池',
  'plage': '海滩；阴性；à la plage 在海滩',
  'réception': '{recev}oir 接待 → réception；英语 reception',
  'télévision': '{télé} 远 + {vision} 看；口语 la télé',
  'terrasse': '{terre} 土地 + {-asse} → 平台；英语 terrace',
  'ville': '拉丁 villa（庄园）→ 城市；英语 village 同根',
  'agence de voyages': '{agence} 代理 + de {voyages} → 旅行社',
  '11:bon(ne)': '好的；bon voyage, bonne journée',
  'conditionné(e)': '{condition} + {-é}（过去分词）→ 被调节的',
  'parfait(e)': '{par} 彻底 + {fait} 做好 → 完美；英语 perfect',
  'on': '口语里常代替 nous；动词用第三人称单数：on est, on visite',
  '11:bien sûr': '当然：Oui, bien sûr !',
  'juste': '英语 just；juste à côté 就在旁边',
  'puis': '然后，同 ensuite、après',
  // Leçon 12
  'aéroport': '{aéro} 空气 + {port} 港 → 航空港；英语 airport',
  'aquarium': '拉丁 {aqua} 水 + {-arium} 场所',
  'art': '英语 art；同 artiste',
  'avion': '拉丁 {avis} 鸟；英语 aviation 同根；en avion 坐飞机',
  'bateau': '英语 boat 同源；复数 bateaux；en bateau',
  'billet': '{bill}e（文书）+ {-et}（小）→ 小纸条 → 票；英语 bill',
  'centre': '英语 centre / center',
  'château': 'â 代替古法语的 s：chastel；英语 castle 同源',
  'hôtel': 'ô 代替古法语的 s：hostel；英语 hostel、hospital、host 同根',
  'hôtel de ville': '{hôtel} 大厦 + de {ville} 城市 → 市政厅',
  'kilomètre': '{kilo} 千 + {mètre} 米；km',
  'office': '英语 office；office de tourisme = 旅游局',
  'palais': '拉丁 palatium；英语 palace',
  'port': '拉丁 portus；英语 port；同 aéroport',
  'quai': '英语 quay（码头）同源',
  'quartier': '{quart} 四分之一 + {-ier} → 城市的一个区；英语 quarter',
  'TGV': 'Train à Grande Vitesse 的首字母：train + grande + vitesse',
  'tourisme': '{tour} 转一圈 + {-isme}；英语 tourism',
  'train': '{traîn}er 拖、拉 → 拖着车厢走的东西；en train',
  'archéologie': '希腊语 {archéo} 古代 + {-logie} 学科；英语 archaeology',
  'bise': '口语，脸颊吻；Grosses bises ! = 亲亲！（信尾）',
  '12:carte': '卡片；carte postale = 明信片',
  'destination': '{destin} 命运、目标 + {-ation}；英语 destination',
  'carte postale': '{carte} 卡 + {postale} 邮政的 → 明信片；英语 postcard',
  'prison': '{pris}（prendre 抓的过去分词）+ {-on} → 关被抓的人的地方',
  'SNCF': 'Société Nationale des Chemins de fer Français：chemin de fer = 铁的路 → 铁路',
  'vitesse': '{vite} 快 + {-esse}（名词后缀）→ 速度',
  'contemporain(e)': '{con-} 共同 + {tempor}（时间）+ {-ain} → 同一时代的；英语 contemporary',
  'gratuit(e)': '拉丁 gratis（免费）；英语 gratis；阳性 t 不发音',
  'intéressant(e)': '{intéress}er 使感兴趣 + {-ant}；英语 interesting，法语双写 s',
  'méditerranéen(enne)': '{medi} 中间 + {terra} 陆地 → 陆地中间的海',
  'postal(e)': '{post}e 邮局 + {-al}；同 carte postale',
  'vieux (vieille)': '元音前阳性用 vieil：un vieil homme；同 vieillesse（老年）',
  'autour de': '{au} + {tour} 一圈 → 在……周围',
  'Marseille': '-eille 读 [ɛj]',
  // Leçon 13
  '13:aller': '动词 {aller}（去）当名词用 → 去程；un aller simple = 单程票',
  'aller-retour': '{aller} 去 + {retour} 回（同 retourner）→ 往返票',
  'départ': '{part}ir 出发 → départ；英语 departure',
  'dimanche': '拉丁 dies dominicus「主的日子」→ di-manche；星期名称都小写、阳性',
  'horaire': '{heure} 小时 → {hor}aire 时刻表；英语 hour',
  'jeudi': '{jeu}（Jupiter 朱庇特）+ {di}（拉丁 dies 日）→ 木星日',
  'lundi': '{lun}e 月亮 + {di} → 月亮日（英语 Monday 也是「月亮日」）',
  'mardi': '{Mar}s 战神 + {di} → 火星日',
  'matin': '早晨；同 matinée（一上午），英语 matinee（日场）',
  'mercredi': '{Mercur}e 墨丘利 + {di} → 水星日',
  'renseignement': '{re-} + {enseign}er（教、指示）+ {-ment} → 问讯、资料；bureau des renseignements = 问讯处',
  'samedi': '拉丁 sabbati dies → 安息日；英语 Sabbath',
  'tarif': '价目；英语 tariff',
  'vendredi': '{Vén}us 维纳斯 + {dredi}（dies）→ 金星日',
  'classe': '英语 class；en deuxième classe = 坐二等座',
  'gare': '火车站；{gar}er（停放）同根，同 garage',
  'heure': '拉丁 hora；英语 hour；h 不发音：une heure [ynœʁ]',
  'pendule': '{pend}re（悬挂）→ 挂钟、钟摆；英语 pendulum',
  '13:place': '这里指座位、空位：il y a de la place = 还有座位',
  'voie': '路、轨道；同 voyage（上路）；la voie 3 = 3 号站台',
  'après-midi': '{après} 之后 + {midi} 中午 → 下午；阴阳性都可以',
  'employé(e)': '{employ}er 雇用 + {-é}（被……的人）→ 雇员；英语 employee',
  'complet(ète)': '英语 complete；火车满员 = complet；阴性 -et → -ète',
  'désolé(e)': '英语 desolate 同根；Je suis désolé(e) = 很抱歉',
  'deuxième': '{deux} 二 + {-ième} → 第二',
  'prochain(e)': '{proche} 近的 + {-ain} → 下一个；mardi prochain = 下周二',
  'simple': '英语 simple；un aller simple = 单程（只有「去」）',
  'quand': 'qu- 疑问家族：quand 什么时候；d 不发音（连读时读 t：quand il）',
  // Leçon 14
  'agenda': '拉丁 agenda「要做的事」→ 日程本；英语 agenda',
  'cabinet': '小房间 → 诊所、事务所；cabinet médical',
  'docteur': '拉丁 doctor（教导者）；英语 doctor',
  'institut': '{institu}er 建立 → 学院、机构；英语 institute',
  'journal': '{jour} 天 + {-al} → 每日出的东西 → 报纸；复数 journaux',
  'reste': '{rest}er 留下 → 剩下的部分；le reste de la semaine',
  'soir': '晚上；同 soirée（整个晚上），bonsoir',
  'coiffure': '{coiff}er 梳头 + {-ure}；同 coiffeur（理发师）',
  'guitare': '英语 guitar',
  'réunion': '{ré-} 再 + {union} 联合 → 聚在一起 → 会议；英语 reunion',
  'semaine': '拉丁 septimana「七天」→ 星期',
  'société': '英语 society；也指公司',
  'surprise': '{sur} 在上 + {pris}（prendre 抓）→ 突然抓住 → 惊喜；Quelle surprise !',
  'vacances': '{vac}ant 空的 → 空闲时间 → 假期；总用复数；英语 vacation',
  'vie': '拉丁 vita；英语 vital；dans la vie = 职业、生活中',
  'acteur(trice)': '{act}e 行动 + {-eur}；阴性 -teur → -trice',
  'informaticien(ienne)': '{informati}que 计算机科学 + {-ien}（从事……的人）；阴性双写 n',
  '14:faire': "qu'est-ce que tu fais dans la vie ? = 你做什么工作？",
  'possible': '英语 possible',
  '14:quel(le)': '感叹用法：Quelle surprise ! = 真是惊喜！',
  'tous, toutes': '{tout} 的复数；tous les jours = 每天；tous 单独作代词时 s 发音',
  '14:là': '这里指「这儿」：qu\'est-ce que tu fais là ?',
  'seulement': '{seul} 唯一的 + {-ement}（副词后缀）→ 只是',
  'tard': '晚；同 retard（迟到）；英语 tardy',
  'tôt': '早；反义 tard；ô 的长音符',
  'donc': '那么、因此；c 有时发音：[dɔ̃k]',
  'mais': '英语 but；这里表示惊讶：Mais c\'est Isabelle !；⚠️ 与 mai（五月）、mes 同音',
  'vers': '朝向、将近：vers 21 h；英语 versus 同根',
  'ben': '口语犹豫词，相当于 bien 的缩音',
  'Londres': '英国伦敦；s 不发音',
  'Vendôme': '法国小城，坐 TGV 到巴黎很快',
  // Leçon 15
  'athlétisme': '{athlète} 运动员 + {-isme}；英语 athletics',
  'déjeuner': '{dé-} 去掉 + {jeûn}er 斋戒 → 结束斋戒 → 吃饭；名词「午饭」与动词「吃午饭」同形',
  'enfant': '拉丁 infans（不会说话的人）；英语 infant',
  'foot': '{foot}ball 的缩写；jouer au foot',
  'footing': '法国人造的英语词，指慢跑；faire un footing',
  'marché': '{march}er 走 → 商人走来走去的地方 → 市场；英语 market',
  'ménage': '{ménag}er 料理家务；faire le ménage = 打扫',
  'petit(-)déjeuner': '{petit} 小 + {déjeuner} 吃饭 → 早餐；有无连字符都对',
  'ski': '借自挪威语；faire du ski',
  'témoignage': '{témoin} 证人 + {-age} → 证词、见证',
  'tennis': '借自英语；jouer au tennis',
  'boîte': '盒子 → 口语「夜总会」：aller en boîte；î 长音符',
  'campagne': '拉丁 campania（平原）→ 乡村；英语 campaign（原指野战）',
  'course': '{cour}ir 跑 → 跑步；复数 les courses = 买东西',
  'gymnastique': '希腊语 gymnos（裸体，指古希腊裸身锻炼）；口语 la gym',
  'natation': '{nat}（拉丁 natare 游）+ {-ation}；同 nager',
  'général(e), pl.m. généraux': '英语 general；-al 复数变 -aux',
  "d'abord": '{à} + {bord}（边）→ 一开始 → 首先；d\'abord … ensuite … après',
  'en général': '{en} + {général} → 一般来说',
  'faire des / les courses': 'les {courses} = 采购；faire les courses 去买东西',
  'faire le ménage': '{ménage} 家务 → 做家务',
  // Leçon 16
  'entraînement': '{entraîn}er 训练 + {-ement}；同 train（拖、拉）',
  'fruit': '英语 fruit；ui 读 [ɥi]',
  'janvier': '拉丁 Januarius（双面神 Janus）；月份小写',
  'jus': '果汁；s 不发音；jus d\'orange',
  'match': '借自英语',
  'stress': '借自英语',
  'yaourt': '来自土耳其语 yoğurt；t 发音',
  'céréales': '{Cérès} 谷物女神 → 谷物；英语 cereal；常用复数',
  'famille': '拉丁 familia；英语 family；-ille 读 [ij]',
  'musculation': '{muscle} 肌肉 + {-ation} → 肌肉训练；口语 la muscu',
  'toilette': '{toile} 布 + {-ette} → 梳洗；faire sa toilette = 洗漱；对比 les toilettes 厕所（复数）',
  'champion(ne)': '英语 champion；阴性双写 n',
  'actuel(le)': '⚠️ 假朋友：「目前的」，不是英语 actual（真实的）；同 actuellement',
  'difficile': '{dif-} 不 + {facile} 容易 → 困难；英语 difficult',
  'habituel(le)': '{habitude} 习惯 + {-el}；英语 habitual',
  'libre': '拉丁 liber（自由）；英语 liberty',
  'long(ue)': '英语 long；阴性 longue（加 u 保持 g 读硬音）',
  'nouveau(nouvelle)': '拉丁 novus；英语 new、novel；元音前阳性用 nouvel',
  'peu': 'un peu 一点；peu 单独用是「很少」',
  'bravo': '借自意大利语：好！',
};
