// English memory tips (英法 mode). Same keys as tips.js; {root} is shown in bold.
window.TIPS_EN = {
  // Leçon 1
  'bonjour': '{bon} good + {jour} day = good day → hello',
  'mari': 'same root as {mari}age (marriage) and se {mari}er (to marry); English marry',
  'monsieur': '{mon} my + {sieur} (lord, as in seigneur) → my lord → sir; say [məsjø]: the "on" sounds like [ə]',
  'nom': 'related to English {name} and Latin {nomen}; prénom = pré (before) + nom',
  'prénom': '{pré} before + {nom} name → the name that comes before the surname',
  'bienvenue': '{bien} well + {venue} come (past participle of venir) → welcome, built just like English "wel-come"',
  'femme': 'pronounced [fam]: "emme" sounds [am]; same root as {fém}inin (feminine)',
  'madame (pl. mesdames)': '{ma} my + {dame} lady; both parts change in the plural: mes + dames',
  'nationalité': '{nation} + {-al} + {-ité}; -ité ≈ English -ity, always feminine',
  'étudiant(e)': '{étudi}er (to study) + {-ant} (one who does) → student',
  'Français(e)': '{France} → {Franç}ais; the cedilla keeps the c soft [s]; capital letter for the person',
  'Italien(ne)': '{Itali}e + {-en}; feminine doubles the n: Italienne; capital for the person',
  'français(e)': 'lower case as an adjective; {-ais} is a common nationality ending (japonais, anglais)',
  'italien(ne)': 'lower case as an adjective; -ien → -ienne doubles the n',
  'ma': 'before feminine singular nouns: ma femme; masculine uses mon',
  'mon': 'before masculine singular nouns: mon mari; also before feminine nouns starting with a vowel (mon adresse)',
  'ce': "c'est = ce + est; drops its e before a vowel",
  'elle': 'pairs with il; plural elles',
  'il': 'from Latin ille (that one); plural ils, the s is silent',
  'je': "becomes j' before a vowel: j'ai, j'habite",
  'qui': 'asks "who"; the qu- family are question words: qui, que, quel, quand',
  'tu': 'for friends and family; use vous with strangers',
  'vous': 'both polite "you" and plural "you"',
  'non': 'English no / non-',
  'oui': 'pronounced [wi], like English "we"',
  'et': 'the t is never pronounced, and never linked to the next word',
  'voici': '{voi}s (look, from voir) + {ci} here → look here → here is',
  // Leçon 2
  'café': 'English coffee / café; é sounds [e]',
  'cours': 'from {cour}ir (to run) → a course that "runs"; English course; same in singular and plural',
  'français': 'languages take lower case, often with le: le français',
  'Japon': 'Japon → {japon}ais (Japanese)',
  'professeur': '{profess}er (to teach publicly) + {-eur} (one who does); English professor, informally prof',
  'rendez-vous': 'literally "present yourselves" → a meeting; neither the z nor the s is pronounced',
  'téléphone': '{télé} far + {phone} sound → a voice from far away; like télévision (far + seeing)',
  'thé': 'English tea; the h is silent',
  'France': 'France → {franç}ais; the ç keeps the [s] sound',
  'Suisse': 'Suisse → {suisse} (Swiss); double s sounds [s]',
  'assistant(e)': '{assist}er (to help) + {-ant}; English assistant',
  'Belge': 'Belgique → {belge}; ends in -e, so masculine and feminine look the same',
  'Chinois(e)': '{Chine} + {-ois}; in chinoise the s sounds [z]',
  'directeur(trice)': '{direct}ion + {-eur}; feminine -teur → -trice (like acteur → actrice); English director',
  'Espagnol(e)': '{Espagne} + {-ol}; gn sounds [ɲ], like "ny" in canyon',
  'Japonais(e)': '{Japon} + {-ais}, a nationality ending',
  'secrétaire': '{secret} + {-aire} → the person who keeps secrets; English secretary',
  'belge': 'lower case as an adjective',
  'chinois(e)': 'lower case as an adjective; le chinois = Chinese (language)',
  'espagnol(e)': "lower case as an adjective; l'espagnol = Spanish (language)",
  'japonais(e)': 'lower case as an adjective; le japonais = Japanese (language)',
  'sympa': 'short for {sympa}thique; English sympathetic; never changes form',
  'à': 'à with an accent is the preposition; a without it is "has" (il a)',
  'dans': 'inside: dans le cours, dans la chambre',
  'en': 'before feminine countries: en France, en Suisse; masculine ones take au: au Japon',
  'ou': '"or" has no accent; où (where) does',
  'ah': 'interjection, silent h',
  'sur rendez-vous': '{sur} on the basis of + rendez-vous → by appointment',
  "s'il vous plaît": '{si} if + {il} + vous {plaît} (it pleases you) → if you please; written SVP',
  'Genève': 'pronounced [ʒənɛv]; English Geneva',
  // Leçon 3
  'âge': 'the circumflex often marks a letter lost from Old French (aage); English age',
  'bébé': 'English baby; two é',
  'Canada': 'masculine country: au Canada',
  'e-mail': 'borrowed from English; French also says courriel (courrier + électronique)',
  'fils': 'pronounced [fis]: silent l, sounded s; English filial shares the root',
  'garçon': 'ç sounds [s]; also means a waiter',
  'adresse': '{a} + {dress}er (to point, to set straight) → where things are directed; French has one d, English address two',
  'fille': '{fil}s son → {fille} daughter; "ill" sounds [ij]',
  'journée': '{jour} day + {-née} (a stretch of time) → the whole day; like soir/soirée, an/année',
  'Notre-Dame': '{notre} our + {dame} lady → Our Lady',
  'rue': 'related to English route; say [ʁy] with rounded lips',
  'ami(e)': 'same root as {am}our and {aim}er; English amicable, amiable',
  'quel(le)': 'qu- question family; quel, quelle, quels, quelles all sound the same',
  'son': 'before masculine singular nouns; "his" or "her" depends on the noun, not the owner',
  'ton': 'before masculine singular nouns; feminine uses ta',
  'votre': 'before singular nouns; plural is vos',
  'ça': 'informal short form of cela; ça va = how are things going',
  'toi': 'stressed form: Et toi ?; the set is moi, toi, lui, elle, nous, vous',
  '3:vous': 'the stressed form looks the same as the subject: Et vous ?',
  'alors': '{à} + {lors} (at that time) → then → so',
  'bien': '{bien} well → {bien}venue; same root as English bene- (benefit)',
  'comment': '{comme} like + -ment → in what way → how',
  'maintenant': '{main} hand + {tenant} (holding, from tenir) → what you hold in your hand → now',
  'avec': 'together with: avec ma femme',
  'merci': 'originally "favour, grace"; English mercy; merci beaucoup',
  'salut': 'originally "health, safety"; English salute; between friends',
  'un(e)': 'indefinite article: un masculine, une feminine',
  'Montréal': '{mont} mountain + {réal} (royal) → royal mountain',
  'Paris': 'silent s: [paʁi]',
  // Leçon 4
  'an': "counting years: j'ai 29 ans; related to année (a whole year), English annual",
  'cinéma': 'Greek kinêma (movement) → cinéma{tographe}; English cinema',
  'espagnol': 'language names are masculine and lower case',
  'golf': 'borrowed from English',
  'monde': 'English mundane shares the root; tout le monde = everybody',
  'Sénégal': 'masculine: au Sénégal → {sénégal}ais',
  'sport': 'borrowed from English',
  'volley-ball': 'borrowed from English volleyball, with a hyphen in French',
  'Belgique': '{belg}e + {-ique}; feminine: en Belgique',
  'correspondance': '{co-} together + {respond}re (to answer) + {-ance}; English uses -ence, French -ance',
  'danse': 'English dance; French uses s',
  'Europe': 'pronounced [øʁɔp]',
  'lecture': '{lect} (Latin legere, to read) + {-ure} → reading; false friend: not a "lecture"',
  'musique': 'English -ic often becomes -ique: music → musique, classic → classique',
  'nature': 'same spelling as English',
  'photo': 'short for {photo}graphie; photo = light, as in photographe',
  'sœur': 'œ sounds [œ]; a distant relative of English sister',
  'boulanger(ère)': '{boule} ball → round loaf → {boulang}erie (bakery); feminine -er → -ère',
  'correspondant(e)': '{correspond}re (to write to each other) + {-ant} → pen pal',
  'classique': 'English -ic → French -ique: classic → classique',
  'guyanais(e)': '{Guyane} + {-ais}',
  'québécois(e)': '{Québec} + {-ois}; keep the é and the c',
  'moi': "stressed form: Moi, c'est Marion.; subject form is je",
  'aussi': 'Latin aliud + {sic} (thus) → likewise, also',
  'beaucoup': '{beau} fine + {coup} blow → a fine stroke → a lot',
  'souvent': 'from Latin subinde; "ou" sounds [u], "ent" sounds [ɑ̃]',
  'un peu': '{peu} little → un peu a little; opposite of beaucoup',
  'de': "becomes d' before a vowel; de + le = du, de + les = des",
  'Bruxelles': 'the x sounds [s]: [bʁysɛl]',
  'Cayenne': 'cayenne pepper is named after it',
  'Dakar': 'capital of Senegal',
  'Lausanne': '"au" sounds [o]',
  // Leçon 5
  'blouson': '{blouse} + {-on} (small, short) → a short jacket',
  'chapeau': 'Latin cappa (cap, cloak); English cap, chaperon; plural chapeaux',
  'côté': 'côte (rib, side) → côté; ô often replaces an old s: English coast',
  'fauteuil': 'armchair; eu sounds [ø], -euil sounds [œj]',
  'lit': 'related to English litter (stretcher); silent t',
  'livre': 'Latin liber (book); English library — but librairie means bookshop',
  'mur': 'English mural shares the root',
  'objet': '{ob-} in front + {jet}er (to throw) → something thrown before you; English object',
  'ordinateur': '{ordin} (order, as in ordre) + {-ateur} (machine) → a machine that puts things in order → computer',
  'sac': 'English sack; the c is sounded',
  'verre': 'Latin vitrum (glass); like vitre (window pane); sounds the same as vert and vers',
  'affiche': '{a-} + {fich}er (to fix) → something fixed to a wall → poster',
  'assiette': 'from {assi}s (seated, from asseoir) → "a setting" → plate',
  'chaise': 'same origin as chaire (pulpit); English chair',
  'chambre': 'English chamber; chambre = bedroom',
  'droite': '{droit} straight / right → la droite; English adroit (right-handed, skilful)',
  'étagère': '{étage} level + {-ère} → shelves in layers; é often matches English s: étage ≈ stage',
  'fenêtre': 'ê replaces an Old French s (fenestre); English defenestrate shares the root',
  'gauche': 'originally "clumsy" — English borrowed gauche; the left hand was thought awkward',
  'table': 'same spelling as English',
  'chat(te)': 'pronounced [ʃa], silent t; feminine chatte',
  'que': "\"what\": qu'est-ce que; part of the qu- family",
  'au-dessous': '{au} + {dessous} (de + sous, below) → underneath',
  'au-dessus': '{au} + {dessus} (de + sur, above) → on top',
  '5:avec': "\"with\" in the sense of having: l'étagère avec des livres",
  'contre': 'English counter / contra-: leaning against, or against',
  'à côté (de)': '{côté} side → à côté de next to',
  '5:de': 'possession: la chambre de Mélanie',
  'devant': '{de} + {avant} before → in front of',
  'à droite (de)': '{droite} right → à droite de',
  'à gauche (de)': '{gauche} left → à gauche de',
  'sous': 'Latin sub; English sub- (subway)',
  'sur': 'Latin super; English sur- (surface)',
  'voilà': '{voi}s look + {là} there → look there → there it is; pairs with voici',
  'il y a': '{y} there + {a} has (avoir) → there has → there is',
  'là': 'là with an accent means "there"; la is the article; Oh là là !',
  'oh': 'interjection, silent h',
  // Leçon 6
  'homme': "Latin homo; English human, homicide; silent h, so l'homme",
  'jean': 'cloth from Genoa (Gênes); pronounced [dʒin]',
  'pantalon': 'from Pantalone, a comedy character who wore long trousers; English pants',
  'portrait-robot': '{portrait} + {robot} → a portrait put together by machine → identikit',
  'tee-shirt': 'borrowed from English T-shirt',
  'vêtement': '{vêt}ir (to dress) + {-ement}; ê replaces s: English vest',
  'basket': 'from English basketball (shoes); usually plural: des baskets',
  'chaussure': '{chausse}r (to put on shoes) + {-ure}; like chaussette (sock)',
  'chemise': 'English chemise (a woman\'s slip) comes from it',
  'chose': 'Latin causa; English cause; autre chose = something else',
  'couleur': '{coul} (Latin color) + {-eur}; British "colour" keeps the French u',
  'lunettes': '{lune} moon + {-ette} (little) → a pair of little moons → glasses; always plural',
  'autre': 'Latin alter; English alter, alternative',
  'blanc(che)': 'English blank; irregular feminine blanche',
  'bleu(e)': 'English blue; eu sounds [ø]',
  'blond(e)': 'English took blond / blonde straight from French',
  'brun(e)': 'English brown; brune sounds [bʁyn]',
  'grand(e)': 'English grand; the d is silent in grand but sounded in grande',
  'leur, leurs': 'leur before a singular noun, leurs before a plural',
  'noir(e)': 'Latin niger; English film noir',
  'petit(e)': 'English petite comes from the feminine form',
  'rouge': 'English rouge (blusher); like rougir (to blush)',
  'vert(e)': 'English verdant; sounds the same as verre (glass)',
  'lui': "stressed form: L'homme brun, lui, il a un blouson.",
  "d'accord": '{de} + {accord} (agreement) → agreed; English accord, according',
  'ne… pas': "wraps around the verb: ils {n'ont pas} de lunettes",
  // Leçon 7
  'euro': 'pronounced [øʁo]; plural euros',
  'pull': 'short for {pull}-over, borrowed from English',
  'shopping': 'borrowed from English; French also says faire les courses',
  'type': 'English type; informally un type also means "a guy"',
  'robe': 'English robe comes from it; in French it means a dress',
  'taille': '{taill}er (to cut) → the cut → size; English tailor shares the root',
  'bon(ne)': 'Ah bon ! = oh really!; feminine doubles the n: bonne',
  'cher(ère)': 'both "expensive" and "dear" (cher ami); English cherish',
  'gris(e)': 'English grizzled (greyish) is related',
  'joli(e)': 'related to English jolly',
  '7:bien': "degree: J'aime bien = I quite like it",
  'combien': '{com}me + {bien} → how much',
  'très': 'from Latin trans (through) → "through and through" → very; très joli',
  '7:et': 'adding numbers: 35 et 59',
  'pour': 'for: pour ma fille',
  '*hum': 'the asterisk marks an aspirated h: no elision, no linking',
  // Leçon 8
  'coin': 'corner; related to English corner (Latin cuneus, wedge)',
  'écrivain': '{écri}re (to write) + {-vain} → writer; é often matches English s: écrire ≈ scribe',
  'film': 'borrowed from English',
  'poème': '{poè}te poet → poème poem; English poem',
  'poète': '{poè}me → poète; English poet',
  'tableau¹': '{table} board + {-eau} (small) → a picture painted on a board; plural tableaux',
  'tableau²': '{table} + {-eau} → a chart; like English "table" of figures',
  'tapis': 'English tapestry; silent s',
  'orange': 'English orange; as a colour adjective it never changes',
  'artiste': '{art} + {-iste} (one who); English artist',
  'môme': 'informal for kid; La Môme ("the kid") was the singer Édith Piaf',
  'musicien(ne)': '{musique} → {music}ien; feminine doubles the n',
  'peintre': '{peind}re (to paint) → peintre; English paint, painter',
  'sculpteur(trice)': '{sculpt}er + {-eur}; the p is silent: [skyltœʁ]; feminine -trice',
  'entre': 'Latin inter; English inter- (international); entre … et …',
  'des': 'de + les = des: à droite des poètes',
  'du': 'de + le = du: à gauche du peintre',
  // Leçon 9
  'appartement': '{appart}enir (to belong) → rooms that belong to someone; informally appart; English apartment has one p',
  'bout': 'au bout de = at the end of',
  'bureau': 'originally the cloth covering a desk → desk → office; plural bureaux; English bureau',
  'couloir': '{coul}er (to flow) + {-oir} (place) → where people flow → corridor',
  'étage': 'é matches English s: étage ≈ stage (a level); like étagère',
  'immeuble': '{im-} not + {meuble} movable → what cannot be moved → building; like immobilier',
  'mètre': 'Greek metron (measure); English metre',
  'mètre carré': '{mètre} + {carré} square → square metre, m²',
  'mois': 'Latin mensis; distantly English month; same in singular and plural',
  'parking': 'borrowed from English',
  'placard': "{plaqu}er (to press flat) → a cupboard set into the wall; false friend: English placard is a sign",
  'plan': 'a flat surface → a floor plan; English plan',
  'rez-de-chaussée': '{rez} (level with) + {de} + {chaussée} (roadway) → the floor level with the street',
  'agence': '{ag}ir (to act) + {-ence} → agency',
  'agence immobilière': '{agence} + {immobilier} (real estate)',
  'annonce': '{a-} + {nonc}er (to declare) → notice; English announce',
  'petite annonce': '{petite} small + {annonce} → a small ad',
  'avenue': '{a-} + {venu} (come) → the way to a place; English avenue',
  'cuisine': '{cuis} (cuire, to cook) + {-ine} → kitchen, cooking; English cuisine',
  'douche': 'English douche comes from it',
  'entrée': '{entr}er (to enter) + {-ée} → entrance; also a starter',
  'face': 'en face de = opposite; English face',
  'salle': 'hall, room; related to English saloon',
  'salle de bains': '{salle} room + {bains} baths → bathroom',
  'toilettes': '{toile} cloth + {-ette} → the little cloth for washing → washroom; always plural',
  'responsable': '{répond}re (to answer) → responsible; English responsible',
  'ancien(ne)': 'English ancient; feminine doubles the n',
  'bruyant(e)': '{bruit} noise + {-ant} → noisy',
  'clair(e)': 'English clear, clarity',
  'immobilier(ère)': '{im-} not + {mobile} movable + {-ier} → real estate; like immeuble',
  'premier(ère)': 'Latin primarius; English premier, prime',
  'récent(e)': 'English recent',
  'sombre': 'English sombre comes from it',
  'troisième': '{trois} three + {-ième} (ordinal ending) → third',
  'où': 'with an accent "where"; without, ou means "or"',
  'chez': 'Latin casa (house) → chez moi = at my place',
  // Leçon 10
  'bus': 'short for auto{bus}',
  'jardin': 'related to English garden; like jardinier (gardener)',
  'métro': 'short for {métro}politain (metropolitan)',
  'musée': '{muse} (the Muses, goddesses of the arts) + {-ée} → home of the Muses; English museum',
  'opéra': 'English opera',
  'pardon': '{par} (completely) + {don} (to give) → forgiveness; English pardon',
  'pied': 'Latin pes, pedis; English pedal, pedestrian; à pied = on foot',
  'pont': 'Latin pons; English pontoon',
  'rollers': 'borrowed from English roller skates',
  'travail': 'English travail (hard toil) is related; plural travaux',
  'vélo': 'short for {vélo}cipède; velo = fast, as in English velocity',
  'banque': 'English -k often becomes -que: bank → banque',
  'ligne': 'English line; gn sounds [ɲ]',
  'moto': 'short for {moto}cyclette; English motor',
  'place': 'a town square; English place, plaza',
  'poste': '{post}e → postal; English post',
  'voiture': 'Latin vectura (transport); distantly English vehicle',
  'direct(e)': 'English direct; like directeur',
  'après': '{a-} + {près} near → right after → after',
  'droit': 'tout droit = straight on',
  'ensuite': '{en} + {suite} (what follows) → next; like suivre (to follow)',
  '10:là': 'there: passez par là',
  'loin': 'far; opposite of près (near)',
  'tout': 'tout droit straight on; as an adverb it means "quite, completely"',
  'jusque': "usually with à, and shortened: jusqu'à, jusqu'au bout",
  'par': 'through: passez par là; English per',
  'bien sûr': '{bien} very + {sûr} sure → of course; English sure',
  // Leçon 11
  'air': 'English air',
  'air conditionné': '{air} + {conditionné} (conditioned) → air conditioning',
  'bar': 'borrowed from English',
  'bord': 'English border, board; au bord de la mer = by the sea',
  'circuit': '{circ}le → a round trip; English circuit',
  'conseil': 'Latin consilium; English counsel',
  'est': 'east; the t is sounded: [ɛst] — not the same as est (is)',
  'hélicoptère': 'Greek {hélico} (spiral) + {ptère} (wing) → spiral wing',
  'jour': 'Latin diurnus; like bonjour, journée; English journal',
  'nord': 'English north',
  'ouest': 'English west; pronounced [wɛst]',
  'restaurant': '{restaur}er (to restore) + {-ant} → a place that restores you; English restore',
  'sud': 'English south; the d is sounded',
  'voyage': '{voie} way + {-age} → being on the road → journey; Bon voyage !',
  'week-end': 'borrowed from English',
  'carte': 'Latin charta (paper); English card, chart',
  'île': 'î replaces an Old French s (isle); English isle, island',
  'mer': 'Latin mare; English marine, mermaid; sounds the same as mère (mother)',
  'piscine': 'Latin piscis (fish) → fish pond → swimming pool',
  'plage': 'beach; feminine: à la plage',
  'réception': '{recev}oir (to receive) → reception',
  'télévision': '{télé} far + {vision} seeing; informally la télé',
  'terrasse': '{terre} earth + {-asse} → a raised platform; English terrace',
  'ville': 'Latin villa (estate) → town; English village',
  'agence de voyages': '{agence} + de {voyages} → travel agency',
  '11:bon(ne)': 'good: bon voyage, bonne journée',
  'conditionné(e)': '{condition} + {-é} (past participle) → conditioned',
  'parfait(e)': '{par} completely + {fait} done → perfect',
  'on': 'often replaces nous in speech; takes the il form of the verb: on est, on visite',
  '11:bien sûr': 'of course: Oui, bien sûr !',
  'juste': 'English just; juste à côté = right next door',
  'puis': 'then, like ensuite and après',
  // Leçon 12
  'aéroport': '{aéro} air + {port} → airport',
  'aquarium': 'Latin {aqua} water + {-arium} (place)',
  'art': 'English art; like artiste',
  'avion': 'Latin {avis} bird; English aviation; en avion = by plane',
  'bateau': 'related to English boat; plural bateaux; en bateau',
  'billet': '{bill}e (document) + {-et} (small) → a slip of paper → ticket; English bill',
  'centre': 'English centre',
  'château': 'â replaces an Old French s (chastel); English castle',
  'hôtel': 'ô replaces an s (hostel); English hostel, hospital, host',
  'hôtel de ville': '{hôtel} (large building) + de {ville} → town hall',
  'kilomètre': '{kilo} thousand + {mètre} → km',
  'office': "English office; office de tourisme = tourist office",
  'palais': 'Latin palatium; English palace',
  'port': 'Latin portus; English port; like aéroport',
  'quai': 'English quay',
  'quartier': '{quart} quarter + {-ier} → a quarter of town; English quarter',
  'TGV': 'Train à Grande Vitesse: train + great + speed',
  'tourisme': '{tour} (a round) + {-isme}; English tourism',
  'train': '{traîn}er (to drag) → something that pulls carriages; en train',
  'archéologie': 'Greek {archéo} ancient + {-logie} (study); English archaeology',
  'bise': 'a kiss on the cheek; Grosses bises ! = lots of love (to end a letter)',
  '12:carte': 'card; carte postale = postcard',
  'destination': '{destin} (fate, aim) + {-ation}; English destination',
  'carte postale': '{carte} + {postale} → postcard',
  'prison': '{pris} (taken, from prendre) + {-on} → where the captured are kept',
  'SNCF': 'Société Nationale des Chemins de fer Français: chemin de fer = iron road → railway',
  'vitesse': '{vite} fast + {-esse} (noun ending) → speed',
  'contemporain(e)': '{con-} together + {tempor} (time) + {-ain} → of the same time; English contemporary',
  'gratuit(e)': 'Latin gratis; English gratis; the t is silent in gratuit',
  'intéressant(e)': '{intéress}er (to interest) + {-ant}; French doubles the s',
  'méditerranéen(enne)': '{medi} middle + {terra} land → the sea in the middle of the lands',
  'postal(e)': '{post}e + {-al}; like carte postale',
  'vieux (vieille)': 'before a vowel the masculine is vieil: un vieil homme; like vieillesse (old age)',
  'autour de': '{au} + {tour} (a turn) → around',
  'Marseille': '-eille sounds [ɛj]',
  // Leçon 13
  '13:aller': 'the verb {aller} (to go) as a noun → outward journey; un aller simple = a single ticket',
  'aller-retour': '{aller} go + {retour} return (as in retourner) → return ticket',
  'départ': '{part}ir (to leave) → départ; English departure',
  'dimanche': 'Latin dies dominicus "the Lord\'s day"; days of the week are lower case and masculine',
  'horaire': '{heure} hour → {hor}aire timetable; English hour',
  'jeudi': '{jeu} (Jupiter) + {di} (Latin dies, day) → Jupiter\'s day',
  'lundi': '{lun}e moon + {di} → moon day, just like English Monday',
  'mardi': '{Mar}s + {di} → Mars\'s day',
  'matin': 'morning; like matinée, English matinee',
  'mercredi': '{Mercur}e + {di} → Mercury\'s day',
  'renseignement': '{re-} + {enseign}er (to show, teach) + {-ment} → information',
  'samedi': 'Latin sabbati dies → Sabbath day',
  'tarif': 'price list; English tariff',
  'vendredi': '{Vén}us + {dredi} (dies) → Venus\'s day',
  'classe': 'English class; en deuxième classe = in second class',
  'gare': 'station; same root as garer (to park), garage',
  'heure': 'Latin hora; English hour; silent h: une heure',
  'pendule': '{pend}re (to hang) → clock, pendulum; English pendulum',
  '13:place': 'here a seat, free space: il y a de la place = there are seats',
  'voie': 'way, track; like voyage; la voie 3 = platform 3',
  'après-midi': '{après} after + {midi} noon → afternoon; masculine or feminine',
  'employé(e)': '{employ}er (to employ) + {-é} → employee',
  'complet(ète)': 'English complete; a full train is complet; feminine -et → -ète',
  'désolé(e)': 'English desolate shares the root; Je suis désolé(e) = I\'m sorry',
  'deuxième': '{deux} two + {-ième} → second',
  'prochain(e)': '{proche} near + {-ain} → next; mardi prochain = next Tuesday',
  'simple': 'English simple; un aller simple = going only one way',
  'quand': 'qu- question family; silent d (sounds t when linked: quand il)',
  // Leçon 14
  'agenda': 'Latin agenda "things to be done" → diary; English agenda',
  'cabinet': 'small room → practice, office; cabinet médical',
  'docteur': 'Latin doctor (teacher); English doctor',
  'institut': '{institu}er (to found) → institute',
  'journal': '{jour} day + {-al} → something that comes out daily → newspaper; plural journaux',
  'reste': '{rest}er (to stay) → what remains; le reste de la semaine',
  'soir': 'evening; like soirée, bonsoir',
  'coiffure': '{coiff}er (to do hair) + {-ure}; like coiffeur (hairdresser)',
  'guitare': 'English guitar',
  'réunion': '{ré-} again + {union} → coming together → meeting; English reunion',
  'semaine': 'Latin septimana "seven days" → week',
  'société': 'English society; also a company',
  'surprise': '{sur} over + {pris} (taken, from prendre) → caught suddenly; Quelle surprise !',
  'vacances': '{vac}ant (empty) → free time → holidays; always plural; English vacation',
  'vie': 'Latin vita; English vital; dans la vie = for a living',
  'acteur(trice)': '{act}e + {-eur}; feminine -teur → -trice',
  'informaticien(ienne)': '{informati}que (computing) + {-ien} (person who); feminine doubles the n',
  '14:faire': "qu'est-ce que tu fais dans la vie ? = what do you do for a living?",
  'possible': 'English possible',
  '14:quel(le)': 'as an exclamation: Quelle surprise ! = what a surprise!',
  'tous, toutes': 'plural of {tout}; tous les jours = every day',
  '14:là': "here: qu'est-ce que tu fais là ?",
  'seulement': '{seul} only, alone + {-ement} (adverb ending) → only',
  'tard': 'late; like retard (delay); English tardy',
  'tôt': 'early; opposite of tard',
  'donc': 'so, therefore; the c is sometimes sounded',
  'mais': "English but; here it shows surprise: Mais c'est Isabelle !",
  'vers': 'towards, around: vers 21 h; English versus',
  'ben': 'spoken hesitation, a clipped bien',
  'Londres': 'London; silent s',
  'Vendôme': 'a small French town, a quick TGV ride from Paris',
  // Leçon 15
  'athlétisme': '{athlète} + {-isme}; English athletics',
  'déjeuner': '{dé-} undo + {jeûn}er (to fast) → break the fast; the noun (lunch) and the verb look the same',
  'enfant': 'Latin infans (one who cannot speak); English infant',
  'foot': 'short for {foot}ball; jouer au foot',
  'footing': 'an English-looking word made in France: jogging; faire un footing',
  'marché': '{march}er (to walk) → where traders walk about → market',
  'ménage': '{ménag}er (to keep house); faire le ménage = to clean',
  'petit(-)déjeuner': '{petit} small + {déjeuner} meal → breakfast; with or without the hyphen',
  'ski': 'from Norwegian; faire du ski',
  'témoignage': '{témoin} witness + {-age} → testimony',
  'tennis': 'borrowed from English; jouer au tennis',
  'boîte': 'box → informally a nightclub: aller en boîte',
  'campagne': 'Latin campania (plain) → countryside; English campaign (first a field battle)',
  'course': '{cour}ir (to run) → a run; plural les courses = shopping',
  'gymnastique': 'Greek gymnos (naked — ancient Greeks trained unclothed); informally la gym',
  'natation': '{nat} (Latin natare, to swim) + {-ation}; like nager',
  'général(e), pl.m. généraux': 'English general; -al becomes -aux in the plural',
  "d'abord": "{à} + {bord} (edge) → at the start → first; d'abord … ensuite … après",
  'en général': '{en} + {général} → in general',
  'faire des / les courses': 'les {courses} = the shopping → to go shopping',
  'faire le ménage': '{ménage} housework → to do the housework',
  // Leçon 16
  'entraînement': '{entraîn}er (to train) + {-ement}; like train',
  'fruit': 'English fruit; ui sounds [ɥi]',
  'janvier': 'Latin Januarius (two-faced god Janus); months are lower case',
  'jus': "juice; silent s; jus d'orange",
  'match': 'borrowed from English',
  'stress': 'borrowed from English',
  'yaourt': 'from Turkish yoğurt; the t is sounded',
  'céréales': '{Cérès}, goddess of grain → cereal; usually plural',
  'famille': 'Latin familia; English family; -ille sounds [ij]',
  'musculation': '{muscle} + {-ation} → weight training; informally la muscu',
  'toilette': '{toile} cloth + {-ette} → washing; faire sa toilette = to have a wash; compare les toilettes (toilet, plural)',
  'champion(ne)': 'English champion; feminine doubles the n',
  'actuel(le)': 'false friend: "current", not English "actual"; like actuellement',
  'difficile': '{dif-} not + {facile} easy → difficult',
  'habituel(le)': '{habitude} habit + {-el}; English habitual',
  'libre': 'Latin liber (free); English liberty',
  'long(ue)': 'English long; feminine longue (the u keeps the g hard)',
  'nouveau(nouvelle)': 'Latin novus; English new, novel; before a vowel the masculine is nouvel',
  'peu': 'un peu = a little; peu alone = not much',
  'bravo': 'borrowed from Italian: well done!',
};
window.VERB_TIPS_EN = {
  'dormir': 'The singular drops the m: dors · dors · dort; the plural keeps it: dormons · dormez · dorment. Same pattern as sortir and partir.',
  'endormir': "en + dormir, conjugated just like dormir: je m'endors · nous nous endormons.",
  'sortir': 'Like partir and dormir: the singular drops the t → sors · sors · sort; the plural puts it back: sortons · sortez · sortent.',
  'écrire': 'Singular écri- + s s t: écris · écris · écrit; the plural adds a v: écrivons · écrivez · écrivent.',
  'lire': 'Singular li- + s s t: lis · lis · lit; the plural adds an s sounded [z]: lisons · lisez · lisent.',
  'voir': 'Singular voi- + s s t; for nous/vous the i becomes y: voyons · voyez; ils voient (back to i).',
  'reprendre': 're + prendre, exactly like prendre: reprends · reprenons · reprennent.',
  'détendre': 'A regular -re verb: drop -re to get détend-, add -s · -s · (nothing) · -ons · -ez · -ent: il se détend (silent d).',
  'lever': 'When the ending is silent the e becomes è: lève · lèves · lève · lèvent; nous/vous keep e: levons · levez. Same as promener.',
  'promener': 'Like lever: e becomes è when the ending is silent: promène · promènent; nous promenons.',
  'manger': 'Only nous is special: mangeons keeps an e so the g stays soft [ʒ]; the rest is regular -er. Same as nager.',
  'nager': 'Like manger: nous nageons keeps the e for the soft g.',
  'commencer': 'Only nous is special: commençons takes ç so the c stays [s] before o. Same as recommencer.',
  'recommencer': 're + commencer: nous recommençons with ç.',
  'être': 'Completely irregular — learn the whole chant: je suis · tu es · il est / nous sommes · vous êtes · ils sont.',
  'avoir': "j'ai · tu as · il a / nous avons · vous avez · ils ont. Don't mix up ils ont (they have, the s links as z) and ils sont (they are).",
  'aller': 'The singular and ils start with v: vais · vas · va · vont; only nous / vous use the stem all-: allons · allez.',
  'faire': 'fais · fais · fait (all sound the same); vous faites (not "faisez"!), ils font.',
  'prendre': 'Singular uses prend- (silent d): prends · prends · prend; nous/vous drop the d: prenons · prenez; ils doubles the n: prennent.',
  'partir': 'The singular drops the t of the stem: pars · pars · part; the plural puts it back: partons · partez · partent.',
  'appeler': "Stem appel + er. When the ending is silent (je / tu / il / ils) write ll: appelle · appelles · appelle · appellent; nous / vous keep one l: appelons · appelez. The pronoun changes too: me · te · se · nous · vous · se, shortened to m' t' s' before a vowel.",
};
